package contracts_test

import (
	"testing"

	contracts "github.com/dopejs/dope-agent/daemon/internal/contracts"
)

func computerUseContractFixtures() map[string]string {
	return map[string]string{
		"schemas/api/create-computer-use-session.request.schema.json":          `{"driverKind":"browser","initialUrl":"https://example.test"}`,
		"schemas/api/computer-use-session-resource.schema.json":                `{"computerUseSessionId":"cusess_1","environmentScope":"test","runId":"run_1","status":"active","driverKind":"browser","currentPage":{"url":"https://example.test","title":"example.test"},"startedAt":"2026-04-22T10:00:00Z","updatedAt":"2026-04-22T10:00:01Z","actions":[]}`,
		"schemas/api/computer-use-session-list.response.schema.json":           `{"items":[{"computerUseSessionId":"cusess_1","environmentScope":"test","runId":"run_1","status":"active","driverKind":"browser","startedAt":"2026-04-22T10:00:00Z","updatedAt":"2026-04-22T10:00:01Z"}]}`,
		"schemas/api/create-computer-use-action.request.schema.json":           `{"actionKind":"input","pageTarget":"active_page","value":"Phase 26","targetMatchContext":{"matchStrategy":"dom_selector","expectedSelector":"#name"}}`,
		"schemas/api/computer-use-action-resource.schema.json":                 `{"computerUseActionId":"cuact_1","environmentScope":"test","computerUseSessionId":"cusess_1","runId":"run_1","actionKind":"input","status":"failed","riskLevel":"high","failureClass":"target_mismatch","failureReason":"approved target no longer matches current page","requestedAt":"2026-04-22T10:00:02Z","updatedAt":"2026-04-22T10:00:03Z","completedAt":"2026-04-22T10:00:03Z","artifacts":[{"artifactId":"cuart_1","environmentScope":"test","computerUseSessionId":"cusess_1","computerUseActionId":"cuact_1","runId":"run_1","kind":"page_snapshot","status":"available","mimeType":"application/json","fileName":"page-snapshot.json","byteSize":10,"storageKey":"computer-use/cusess_1/cuart_1","sha256":"abc","createdAt":"2026-04-22T10:00:03Z"}]}`,
		"schemas/api/computer-use-action-list.response.schema.json":            `{"items":[{"computerUseActionId":"cuact_1","environmentScope":"test","computerUseSessionId":"cusess_1","runId":"run_1","actionKind":"navigate","status":"completed","riskLevel":"low","requestedAt":"2026-04-22T10:00:02Z","updatedAt":"2026-04-22T10:00:03Z"}]}`,
		"schemas/api/computer-use-artifact-resource.schema.json":               `{"artifactId":"cuart_1","environmentScope":"test","computerUseSessionId":"cusess_1","computerUseActionId":"cuact_1","runId":"run_1","kind":"page_snapshot","status":"available","mimeType":"application/json","fileName":"page-snapshot.json","byteSize":10,"storageKey":"computer-use/cusess_1/cuart_1","sha256":"abc","createdAt":"2026-04-22T10:00:03Z"}`,
		"schemas/api/computer-use-artifact-content.response.schema.json":       `{"artifactId":"cuart_1","mimeType":"application/json","fileName":"page-snapshot.json","status":"available","content":"ZXhhbXBsZQ=="}`,
		"schemas/api/workflow-step-resource.schema.json":                       `{"workflowStepId":"wfstep_browser_1","workflowId":"wf_1","title":"Inspect deterministic browser fixture","position":1,"consumerKind":"computer_use","consumerId":"browser","toolName":"browser","status":"completed","runtimeStepId":"step_1","activeToolCallId":"toolcall_1","attemptCount":1,"maxAttempts":1,"computerUseSessionId":"cusess_1","computerUseActionIds":["cuact_nav_1","cuact_snap_1"],"computerUseArtifacts":[{"artifactId":"cuart_1","environmentScope":"test","computerUseSessionId":"cusess_1","computerUseActionId":"cuact_snap_1","runId":"run_1","kind":"page_snapshot","status":"available","mimeType":"application/json","fileName":"page-snapshot.json","byteSize":10,"storageKey":"computer-use/cusess_1/cuart_1","sha256":"abc","createdAt":"2026-04-22T10:00:03Z"}],"createdAt":"2026-04-22T10:00:00Z","updatedAt":"2026-04-22T10:00:03Z"}`,
		"schemas/api/tool-call-resource.schema.json":                           `{"toolCallId":"toolcall_1","runId":"run_1","stepId":"step_1","workflowId":"wf_1","workflowStepId":"wfstep_browser_1","computerUseSessionId":"cusess_1","computerUseActionId":"cuact_snap_1","invocationKind":"local_tool","capabilityId":"browser","toolName":"snapshot","status":"completed","createdAt":"2026-04-22T10:00:02Z","updatedAt":"2026-04-22T10:00:03Z","output":{"computerUseSessionId":"cusess_1","computerUseActionId":"cuact_snap_1"}}`,
		"schemas/api/tool-call-list.response.schema.json":                      `{"items":[{"toolCallId":"toolcall_1","runId":"run_1","stepId":"step_1","workflowId":"wf_1","workflowStepId":"wfstep_browser_1","computerUseSessionId":"cusess_1","computerUseActionId":"cuact_snap_1","invocationKind":"local_tool","capabilityId":"browser","toolName":"snapshot","status":"completed","createdAt":"2026-04-22T10:00:02Z","updatedAt":"2026-04-22T10:00:03Z"}]}`,
		"schemas/events/runtime-event.schema.json":                             `{"eventId":"evt_runtime_1","sequence":1,"category":"capability","name":"computer_use.action_status_changed","occurredAt":"2026-04-22T10:00:03Z","scope":{"runId":"run_1","stepId":"step_1","computerUseSessionId":"cusess_1","computerUseActionId":"cuact_1"},"resource":{"kind":"computer_use_action","id":"cuact_1"},"payload":{"status":"failed","failureClass":"target_mismatch"}}`,
		"schemas/events/computer-use-session-created.event.schema.json":        `{"eventId":"evt_1","sequence":1,"category":"capability","name":"computer_use.session_created","occurredAt":"2026-04-22T10:00:00Z","scope":{"runId":"run_1","computerUseSessionId":"cusess_1"},"resource":{"kind":"computer_use_session","id":"cusess_1"},"payload":{"status":"active","computerUseSessionId":"cusess_1"}}`,
		"schemas/events/computer-use-session-status-changed.event.schema.json": `{"eventId":"evt_2","sequence":2,"category":"capability","name":"computer_use.session_status_changed","occurredAt":"2026-04-22T10:00:01Z","scope":{"runId":"run_1","computerUseSessionId":"cusess_1"},"resource":{"kind":"computer_use_session","id":"cusess_1"},"payload":{"status":"closed","computerUseSessionId":"cusess_1"}}`,
		"schemas/events/computer-use-action-requested.event.schema.json":       `{"eventId":"evt_3","sequence":3,"category":"capability","name":"computer_use.action_requested","occurredAt":"2026-04-22T10:00:02Z","scope":{"runId":"run_1","stepId":"step_1","computerUseSessionId":"cusess_1","computerUseActionId":"cuact_1"},"resource":{"kind":"computer_use_action","id":"cuact_1"},"payload":{"status":"waiting_approval","actionKind":"input","computerUseSessionId":"cusess_1","computerUseActionId":"cuact_1"}}`,
		"schemas/events/computer-use-action-status-changed.event.schema.json":  `{"eventId":"evt_4","sequence":4,"category":"capability","name":"computer_use.action_status_changed","occurredAt":"2026-04-22T10:00:03Z","scope":{"runId":"run_1","stepId":"step_1","computerUseSessionId":"cusess_1","computerUseActionId":"cuact_1"},"resource":{"kind":"computer_use_action","id":"cuact_1"},"payload":{"status":"completed","computerUseSessionId":"cusess_1","computerUseActionId":"cuact_1"}}`,
		"schemas/events/computer-use-action-target-mismatch.event.schema.json": `{"eventId":"evt_5","sequence":5,"category":"capability","name":"computer_use.action_target_mismatch","occurredAt":"2026-04-22T10:00:04Z","scope":{"runId":"run_1","stepId":"step_1","computerUseSessionId":"cusess_1","computerUseActionId":"cuact_1"},"resource":{"kind":"computer_use_action","id":"cuact_1"},"payload":{"status":"failed","failureClass":"target_mismatch","computerUseSessionId":"cusess_1","computerUseActionId":"cuact_1"}}`,
		"schemas/events/computer-use-artifact-recorded.event.schema.json":      `{"eventId":"evt_6","sequence":6,"category":"capability","name":"computer_use.artifact_recorded","occurredAt":"2026-04-22T10:00:05Z","scope":{"runId":"run_1","computerUseSessionId":"cusess_1","computerUseActionId":"cuact_1"},"resource":{"kind":"computer_use_artifact","id":"cuart_1"},"payload":{"artifactId":"cuart_1","artifactKind":"page_snapshot","captureStatus":"available"}}`,
	}
}

func assertComputerUseContractFixtures(t *testing.T, validator *contracts.Validator) {
	t.Helper()
	mustValidateFixtures(t, validator, computerUseContractFixtures())
}

func TestComputerUseSchemasAcceptCanonicalFixtures(t *testing.T) {
	t.Parallel()

	validator := contracts.NewValidator(schemaRootDir(t))
	assertComputerUseContractFixtures(t, validator)
}
