package contracts_test

import (
	"strings"
	"testing"

	contracts "github.com/dopejs/dope-agent/daemon/internal/contracts"
)

func connectorConformanceContractFixtures() map[string]string {
	return map[string]string{
		"schemas/api/connector-capability-profile.schema.json":                    `{"connectorKind":"discord","connectorId":"connector_discord_test","lifecycleState":"healthy","surfaces":{"direct_message":"supported","group_channel":"supported","thread_reply":"limited","incremental_update":"unsupported","background_delivery":"supported"},"identityRules":{"durableIdentity":"tenant_id + connector_account_id + channel_or_conversation_id + provider_message_id","equivalentIdentity":"provider_message_id aliases webhook delivery id when provider supplies both"},"coreInvariants":{"tenant_scoped_identity":"pass","dedupe":"pass","foreground_background_separation":"pass","redacted_diagnostics":"pass"},"generatedAt":"2026-05-07T10:00:00Z","retentionExpiresAt":"2026-08-05T10:00:00Z","redactionStatus":"redacted"}`,
		"schemas/api/connector-conformance-result.schema.json":                    `{"conformanceResultId":"conformance_result_1","tenantId":"ten_033","connectorKind":"discord","connectorId":"connector_discord_test","scenarioId":"discord.thread_reply.limited","area":"thread_reply","result":"limited","reasonCode":"unsupported_capability","evidenceTimestamp":"2026-05-07T10:00:00Z","redactionStatus":"redacted","retentionExpiresAt":"2026-08-05T10:00:00Z","evidenceSummary":"Thread reply is recorded as limited while direct messages pass core invariants."}`,
		"schemas/api/connector-diagnostic-state.schema.json":                      `{"diagnosticStateId":"diagnostic_state_1","tenantId":"ten_033","connectorId":"connector_discord_test","connectorAccountId":"acct_redacted","status":"degraded","reasonCode":"rate_limited","remediationOwner":"provider","userVisibleSeverity":"warning","retrySafety":"retry_after","freshnessState":"fresh","evidenceTimestamp":"2026-05-07T10:00:00Z","staleAfter":"2026-05-07T10:15:00Z","redactionStatus":"redacted","retentionExpiresAt":"2026-08-05T10:00:00Z"}`,
		"schemas/api/connector-account-binding-summary.schema.json":               `{"tenantId":"ten_033","connectorId":"connector_discord_test","connectorAccountId":"acct_redacted","displayName":"Discord workspace","providerAccountHint":"discord:guild_redacted","redactionStatus":"redacted","updatedAt":"2026-05-07T10:00:00Z"}`,
		"schemas/api/connector-resource.schema.json":                              `{"tenantId":"ten_033","connectorId":"connector_discord_test","kind":"discord","displayName":"Discord","status":"healthy","failureCount":0,"restartCount":1,"backoffSeconds":0,"createdAt":"2026-05-07T09:00:00Z","updatedAt":"2026-05-07T10:00:00Z","capabilityProfile":{"connectorKind":"discord","connectorId":"connector_discord_test","lifecycleState":"healthy","surfaces":{"direct_message":"supported"},"identityRules":{"durableIdentity":"tenant_id + connector_account_id + channel_or_conversation_id + provider_message_id"},"coreInvariants":{"tenant_scoped_identity":"pass"},"generatedAt":"2026-05-07T10:00:00Z","retentionExpiresAt":"2026-08-05T10:00:00Z","redactionStatus":"redacted"},"diagnosticState":{"diagnosticStateId":"diagnostic_state_1","tenantId":"ten_033","connectorId":"connector_discord_test","status":"healthy","reasonCode":"healthy","remediationOwner":"none_required","userVisibleSeverity":"info","retrySafety":"no_action_needed","freshnessState":"fresh","evidenceTimestamp":"2026-05-07T10:00:00Z","redactionStatus":"redacted","retentionExpiresAt":"2026-08-05T10:00:00Z"},"conformanceResult":{"conformanceResultId":"conformance_result_1","tenantId":"ten_033","connectorKind":"discord","connectorId":"connector_discord_test","scenarioId":"discord.direct.pass","area":"direct_message","result":"pass","evidenceTimestamp":"2026-05-07T10:00:00Z","redactionStatus":"redacted","retentionExpiresAt":"2026-08-05T10:00:00Z"},"accountBinding":{"tenantId":"ten_033","connectorId":"connector_discord_test","connectorAccountId":"acct_redacted","redactionStatus":"redacted","updatedAt":"2026-05-07T10:00:00Z"}}`,
		"schemas/events/connector-conformance-result-recorded.event.schema.json":  `{"eventId":"evt_connector_conformance_1","sequence":1,"category":"connector","name":"connector.conformance_result_recorded","occurredAt":"2026-05-07T10:00:00Z","scope":{"connectorId":"connector_discord_test"},"resource":{"kind":"connector_conformance_result","id":"conformance_result_1"},"payload":{"tenantId":"ten_033","conformanceResultId":"conformance_result_1","connectorKind":"discord","connectorId":"connector_discord_test","scenarioId":"discord.direct.pass","area":"direct_message","result":"pass","redactionStatus":"redacted","retentionExpiresAt":"2026-08-05T10:00:00Z"}}`,
		"schemas/events/connector-diagnostic-state-changed.event.schema.json":     `{"eventId":"evt_connector_diagnostic_1","sequence":2,"category":"connector","name":"connector.diagnostic_state_changed","occurredAt":"2026-05-07T10:01:00Z","scope":{"connectorId":"connector_discord_test"},"resource":{"kind":"connector_diagnostic_state","id":"diagnostic_state_1"},"payload":{"tenantId":"ten_033","diagnosticStateId":"diagnostic_state_1","connectorId":"connector_discord_test","previousStatus":"healthy","status":"degraded","reasonCode":"rate_limited","remediationOwner":"provider","retrySafety":"retry_after","freshnessState":"fresh","redactionStatus":"redacted"}}`,
		"schemas/events/connector-diagnostic-redaction-failed.event.schema.json":  `{"eventId":"evt_connector_diagnostic_2","sequence":3,"category":"connector","name":"connector.diagnostic_redaction_failed","occurredAt":"2026-05-07T10:02:00Z","scope":{"connectorId":"connector_discord_test"},"resource":{"kind":"connector_diagnostic_redaction_failure","id":"redaction_failure_1"},"payload":{"tenantId":"ten_033","connectorId":"connector_discord_test","targetKind":"diagnostic_state","targetId":"diagnostic_state_1","reasonCode":"redaction_failed_closed","redactionStatus":"suppressed","retentionExpiresAt":"2026-08-05T10:02:00Z"}}`,
		"schemas/events/connector-inbound-duplicate-detected.event.schema.json":   `{"eventId":"evt_connector_duplicate_1","sequence":4,"category":"connector","name":"connector.inbound_duplicate_detected","occurredAt":"2026-05-07T10:03:00Z","scope":{"connectorId":"connector_discord_test"},"resource":{"kind":"connector_message","id":"msg_duplicate_1"},"payload":{"tenantId":"ten_033","connectorId":"connector_discord_test","connectorAccountId":"acct_redacted","channelOrConversationId":"chan_redacted","providerMessageId":"provider_msg_1","equivalentRuleId":"discord_message_id","existingDeliveryId":"delivery_1","redactionStatus":"redacted"}}`,
		"schemas/events/connector-route-outcome-recorded.event.schema.json":       `{"eventId":"evt_connector_route_1","sequence":5,"category":"connector","name":"connector.route_outcome_recorded","occurredAt":"2026-05-07T10:04:00Z","scope":{"connectorId":"connector_discord_test"},"resource":{"kind":"connector_route_outcome","id":"route_outcome_1"},"payload":{"tenantId":"ten_033","connectorId":"connector_discord_test","outcome":"blocked","reasonCode":"blocked_route","surface":"group_channel","messageDeliveryId":"delivery_1","redactionStatus":"redacted"}}`,
		"schemas/events/connector-foreground-reply-failed.event.schema.json":      `{"eventId":"evt_connector_reply_failed_1","sequence":6,"category":"connector","name":"connector.foreground_reply_failed","occurredAt":"2026-05-07T10:05:00Z","scope":{"connectorId":"connector_discord_test","sessionId":"session_1","runId":"run_1"},"resource":{"kind":"connector_foreground_reply","id":"foreground_reply_1"},"payload":{"tenantId":"ten_033","connectorId":"connector_discord_test","messageDeliveryId":"delivery_reply_1","status":"failed","reasonCode":"transport_failed","retrySafety":"retryable","backgroundDeliveryId":"delivery_background_1","separationStatus":"separate_truths","redactionStatus":"redacted"}}`,
		"schemas/events/connector-delivery-separation-recorded.event.schema.json": `{"eventId":"evt_connector_delivery_boundary_1","sequence":7,"category":"connector","name":"connector.delivery_separation_recorded","occurredAt":"2026-05-07T10:06:00Z","scope":{"connectorId":"connector_discord_test"},"resource":{"kind":"connector_delivery_boundary","id":"boundary_1"},"payload":{"tenantId":"ten_033","connectorId":"connector_discord_test","foregroundReplyOutcomeId":"foreground_reply_1","backgroundDeliveryId":"delivery_background_1","transportKind":"discord","separationStatus":"separate_truths","redactionStatus":"redacted"}}`,
	}
}

func TestConnectorConformanceSchemasAcceptCanonicalFixtures(t *testing.T) {
	t.Parallel()

	validator := contracts.NewValidator(schemaRootDir(t))
	mustValidateFixtures(t, validator, connectorConformanceContractFixtures())
}

func TestConnectorConformanceSchemasAcceptTelegramFixtures(t *testing.T) {
	t.Parallel()

	validator := contracts.NewValidator(schemaRootDir(t))
	mustValidateFixtures(t, validator, map[string]string{
		"schemas/api/connector-capability-profile.schema.json": `{"connectorKind":"telegram","connectorId":"telegram-main","lifecycleState":"healthy","surfaces":{"direct_message":"supported","group_message":"supported","mention_gating":"supported","command_gating":"supported","attachments":"unsupported","voice":"unsupported","payments":"unsupported","mini_apps":"unsupported","background_delivery":"supported"},"identityRules":{"durableIdentity":"tenant_id + connector_account_id + telegram_chat_id + telegram_message_id","equivalentIdentity":"telegram_update_id retained only as redacted evidence"},"coreInvariants":{"tenant_scoped_identity":"pass","dedupe":"pass","foreground_background_separation":"pass","redacted_diagnostics":"pass"},"generatedAt":"2026-05-08T10:00:00Z","retentionExpiresAt":"2026-08-06T10:00:00Z","redactionStatus":"redacted"}`,
		"schemas/api/connector-conformance-result.schema.json": `{"conformanceResultId":"conformance_telegram_1","tenantId":"ten_telegram","connectorKind":"telegram","connectorId":"telegram-main","scenarioId":"telegram.group.command.accepted","area":"command_gating","result":"pass","reasonCode":"matched","evidenceTimestamp":"2026-05-08T10:00:00Z","redactionStatus":"redacted","retentionExpiresAt":"2026-08-06T10:00:00Z","evidenceSummary":"Allowed Telegram group command gating accepted one redacted text update."}`,
		"schemas/api/connector-resource.schema.json":           `{"tenantId":"ten_telegram","connectorId":"telegram-main","kind":"telegram","displayName":"Telegram Main","status":"healthy","failureCount":0,"restartCount":0,"backoffSeconds":0,"createdAt":"2026-05-08T09:00:00Z","updatedAt":"2026-05-08T10:00:00Z","capabilityProfile":{"connectorKind":"telegram","connectorId":"telegram-main","lifecycleState":"healthy","surfaces":{"direct_message":"supported","group_message":"supported","attachments":"unsupported"},"identityRules":{"durableIdentity":"tenant_id + connector_account_id + telegram_chat_id + telegram_message_id"},"coreInvariants":{"tenant_scoped_identity":"pass"},"generatedAt":"2026-05-08T10:00:00Z","retentionExpiresAt":"2026-08-06T10:00:00Z","redactionStatus":"redacted"},"conformanceResult":{"conformanceResultId":"conformance_telegram_1","tenantId":"ten_telegram","connectorKind":"telegram","connectorId":"telegram-main","scenarioId":"telegram.direct.pass","area":"direct_message","result":"pass","evidenceTimestamp":"2026-05-08T10:00:00Z","redactionStatus":"redacted","retentionExpiresAt":"2026-08-06T10:00:00Z"}}`,
	})
}

func TestConnectorConformanceSchemasAcceptSlackFixtures(t *testing.T) {
	t.Parallel()

	validator := contracts.NewValidator(schemaRootDir(t))
	mustValidateFixtures(t, validator, map[string]string{
		"schemas/api/connector-capability-profile.schema.json": `{"connectorKind":"slack","connectorId":"slack-main","lifecycleState":"healthy","surfaces":{"hosted_oauth_setup":"supported","submitted_token_setup":"unsupported","workspace_binding":"supported","direct_message":"supported","selected_channel_mention":"supported","channel_thread_reply":"supported","final_only_foreground_reply":"supported","connector_backed_delivery":"supported","marketplace_publication":"unsupported","enterprise_grid_administration":"unsupported","memory_based_team_context":"unsupported","files":"unsupported","voice_huddles":"unsupported","canvases":"unsupported","workflow_buttons":"unsupported","interactive_blocks":"unsupported","rich_media":"unsupported","thinking_visibility":"unsupported","incremental_visible_updates":"unsupported"},"identityRules":{"durableIdentity":"tenant_id + connector_id + workspace_id + conversation_id + slack_message_id","equivalentIdentity":"slack event_id retained only as redacted delivery evidence"},"coreInvariants":{"tenant_scoped_identity":"pass","dedupe":"pass","foreground_background_separation":"pass","redacted_diagnostics":"pass"},"generatedAt":"2026-05-08T10:00:00Z","retentionExpiresAt":"2026-08-06T10:00:00Z","redactionStatus":"redacted"}`,
		"schemas/api/connector-conformance-result.schema.json": `{"conformanceResultId":"conformance_slack_1","tenantId":"ten_slack","connectorKind":"slack","connectorId":"slack-main","scenarioId":"slack.channel_mention.thread_reply","area":"thread_reply","result":"pass","reasonCode":"matched","evidenceTimestamp":"2026-05-08T10:00:00Z","redactionStatus":"redacted","retentionExpiresAt":"2026-08-06T10:00:00Z","evidenceSummary":"Selected Slack channel mention produced one final-only thread reply with redacted identity evidence."}`,
		"schemas/api/connector-resource.schema.json":           `{"tenantId":"ten_slack","connectorId":"slack-main","kind":"slack","displayName":"Slack Main","status":"healthy","failureCount":0,"restartCount":0,"backoffSeconds":0,"createdAt":"2026-05-08T09:00:00Z","updatedAt":"2026-05-08T10:00:00Z","capabilityProfile":{"connectorKind":"slack","connectorId":"slack-main","lifecycleState":"healthy","surfaces":{"hosted_oauth_setup":"supported","direct_message":"supported","selected_channel_mention":"supported","files":"unsupported"},"identityRules":{"durableIdentity":"tenant_id + connector_id + workspace_id + conversation_id + slack_message_id"},"coreInvariants":{"tenant_scoped_identity":"pass"},"generatedAt":"2026-05-08T10:00:00Z","retentionExpiresAt":"2026-08-06T10:00:00Z","redactionStatus":"redacted"},"conformanceResult":{"conformanceResultId":"conformance_slack_1","tenantId":"ten_slack","connectorKind":"slack","connectorId":"slack-main","scenarioId":"slack.direct.pass","area":"direct_message","result":"pass","evidenceTimestamp":"2026-05-08T10:00:00Z","redactionStatus":"redacted","retentionExpiresAt":"2026-08-06T10:00:00Z"}}`,
	})
}

func TestConnectorRedactionFailureFixtureSuppressesProviderSecrets(t *testing.T) {
	t.Parallel()

	fixture := connectorConformanceContractFixtures()["schemas/events/connector-diagnostic-redaction-failed.event.schema.json"]
	lower := strings.ToLower(fixture)
	for _, token := range []string{"secret", "token", "authorization", "rawproviderpayload"} {
		if strings.Contains(lower, token) {
			t.Fatalf("redaction failure fixture leaked sensitive marker %q: %s", token, fixture)
		}
	}
	if !strings.Contains(fixture, `"redactionStatus":"suppressed"`) {
		t.Fatalf("expected fail-closed redaction status in fixture: %s", fixture)
	}
}
