package contracts_test

import (
	"testing"

	contracts "github.com/dopejs/dope-agent/daemon/internal/contracts"
)

func integrationDiagnosticContractFixtures() map[string]string {
	return map[string]string{
		"schemas/api/integration-diagnostic-reason-code.schema.json":                `{"reasonCode":"healthy","category":"healthy","defaultRetrySafety":"no_action_needed","defaultRemediationOwner":"none_required","userMessageKey":"integration.diagnostic.healthy","operatorMessageKey":"integration.diagnostic.healthy","supportedDomains":["calendar"]}`,
		"schemas/api/integration-diagnostic-result.schema.json":                     `{"diagnosticResultId":"diag_result_1","tenantId":"ten_r42","integrationId":"integration_calendar_feishu","integrationAccountId":"acct_redacted","domainKind":"calendar","providerKind":"feishu_lark","capability":"calendar.read","status":"healthy","reasonCode":"healthy","remediationOwner":"none_required","remediationHint":"No action needed.","retrySafety":"no_action_needed","checkedAt":"2026-04-30T10:00:00Z","staleAfter":"2026-04-30T10:15:00Z","freshnessState":"fresh","runId":"diag_run_1","redactionStatus":"redacted","evidenceSummary":"provider ready","retentionExpiresAt":"2026-07-29T10:00:00Z"}`,
		"schemas/api/integration-diagnostic-run.schema.json":                        `{"diagnosticRunId":"diag_run_1","tenantId":"ten_r42","integrationId":"integration_calendar_feishu","integrationAccountId":"acct_redacted","domainKind":"calendar","providerKind":"feishu_lark","status":"completed","trigger":"operator_inspection","requestedBy":"operator_r42","startedAt":"2026-04-30T10:00:00Z","completedAt":"2026-04-30T10:01:00Z","checkedCapabilities":["calendar.read"],"resultIds":["diag_result_1"],"redactionStatus":"redacted","retentionExpiresAt":"2026-07-29T10:00:00Z"}`,
		"schemas/api/integration-diagnostic-list.response.schema.json":              `{"integrationId":"integration_calendar_feishu","tenantId":"ten_r42","freshnessSummary":"latest diagnostic state","items":[{"diagnosticResultId":"diag_result_1","tenantId":"ten_r42","integrationId":"integration_calendar_feishu","domainKind":"calendar","providerKind":"feishu_lark","capability":"calendar.read","status":"healthy","reasonCode":"healthy","remediationOwner":"none_required","retrySafety":"no_action_needed","checkedAt":"2026-04-30T10:00:00Z","staleAfter":"2026-04-30T10:15:00Z","freshnessState":"fresh","redactionStatus":"redacted","retentionExpiresAt":"2026-07-29T10:00:00Z"}]}`,
		"schemas/api/create-integration-diagnostic-run.request.schema.json":         `{"capabilities":["calendar.read"],"forceRefresh":true,"clientKey":"client_r42","reason":"operator inspection"}`,
		"schemas/api/create-integration-diagnostic-smoke.request.schema.json":       `{"reportId":"smoke_feishu_probe","integrationId":"integration_calendar_feishu","probes":[{"domainKind":"calendar","probeAction":"calendar.read","safeCredentialsAvailable":true,"tenantApprovalAvailable":true,"providerAvailable":true,"supported":true,"readOnlyOrReversible":true,"providerEvidence":{"code":"scope_not_granted"}}]}`,
		"schemas/api/integration-diagnostic-failure-projection.schema.json":         `{"reasonCode":"tenant_approval_pending","remediationOwner":"tenant_admin","remediationHint":"Ask a tenant administrator to approve the provider application.","retrySafety":"blocked","freshnessState":"fresh","checkedAt":"2026-04-30T10:00:00Z","redactionStatus":"redacted"}`,
		"schemas/api/smoke-probe-outcome.schema.json":                               `{"probeOutcomeId":"probe_1","smokeReportId":"smoke_1","tenantId":"ten_r42","integrationId":"integration_calendar_feishu","integrationAccountId":"acct_redacted","domainKind":"calendar","providerKind":"feishu_lark","probeAction":"calendar.read","result":"passed","reasonCode":"healthy","remediationHint":"No action needed.","retrySafety":"no_action_needed","artifactRefs":["artifact_1"],"checkedAt":"2026-04-30T10:01:00Z","redactionStatus":"redacted","retentionExpiresAt":"2026-07-29T10:01:00Z"}`,
		"schemas/api/smoke-matrix-report.schema.json":                               `{"smokeReportId":"smoke_1","tenantId":"ten_r42","reportKind":"diagnostic","requestedBy":"operator_r42","status":"completed","startedAt":"2026-04-30T10:00:00Z","completedAt":"2026-04-30T10:03:00Z","domainSummary":{"calendar":"passed","mail":"blocked"},"artifactRefs":["artifact_1"],"retentionExpiresAt":"2026-07-29T10:03:00Z"}`,
		"schemas/events/integration-diagnostic-run-started.event.schema.json":       `{"eventId":"evt_diag_1","sequence":1,"category":"integration","name":"integration_diagnostic.run_started","occurredAt":"2026-04-30T10:00:00Z","scope":{},"resource":{"kind":"integration_diagnostic_run","id":"diag_run_1"},"payload":{"tenantId":"ten_r42","diagnosticRunId":"diag_run_1","integrationId":"integration_calendar_feishu","requestedBy":"operator_r42","status":"running"}}`,
		"schemas/events/integration-diagnostic-run-completed.event.schema.json":     `{"eventId":"evt_diag_2","sequence":2,"category":"integration","name":"integration_diagnostic.run_completed","occurredAt":"2026-04-30T10:01:00Z","scope":{},"resource":{"kind":"integration_diagnostic_run","id":"diag_run_1"},"payload":{"tenantId":"ten_r42","diagnosticRunId":"diag_run_1","integrationId":"integration_calendar_feishu","status":"completed","resultIds":["diag_result_1"],"redactionStatus":"redacted"}}`,
		"schemas/events/integration-diagnostic-state-changed.event.schema.json":     `{"eventId":"evt_diag_3","sequence":3,"category":"integration","name":"integration_diagnostic.state_changed","occurredAt":"2026-04-30T10:01:00Z","scope":{},"resource":{"kind":"integration_diagnostic_result","id":"diag_result_1"},"payload":{"tenantId":"ten_r42","diagnosticResultId":"diag_result_1","integrationId":"integration_calendar_feishu","previousStatus":"unknown","status":"healthy","reasonCode":"healthy","remediationOwner":"none_required"}}`,
		"schemas/events/integration-diagnostic-redaction-failed.event.schema.json":  `{"eventId":"evt_diag_4","sequence":4,"category":"integration","name":"integration_diagnostic.redaction_failed_closed","occurredAt":"2026-04-30T10:02:00Z","scope":{},"resource":{"kind":"integration_diagnostic_result","id":"diag_result_2"},"payload":{"tenantId":"ten_r42","targetKind":"diagnostic_result","targetId":"diag_result_2","reasonCode":"redaction_failed_closed","redactionStatus":"failed_closed"}}`,
		"schemas/events/integration-diagnostic-smoke-completed.event.schema.json":   `{"eventId":"evt_diag_5","sequence":5,"category":"integration","name":"integration_diagnostic.smoke_completed","occurredAt":"2026-04-30T10:03:00Z","scope":{},"resource":{"kind":"integration_diagnostic_smoke_report","id":"smoke_1"},"payload":{"tenantId":"ten_r42","smokeReportId":"smoke_1","status":"completed","domainSummary":{"calendar":"passed"},"artifactRefs":["artifact_1"]}}`,
		"schemas/events/integration-diagnostic-retention-applied.event.schema.json": `{"eventId":"evt_diag_6","sequence":6,"category":"integration","name":"integration_diagnostic.retention_applied","occurredAt":"2026-04-30T10:04:00Z","scope":{},"resource":{"kind":"integration_diagnostic_retention","id":"retention_1"},"payload":{"tenantId":"ten_r42","targetKind":"diagnostic_run","targetId":"diag_run_1","retentionState":"active","effectiveExpiresAt":"2026-07-29T10:00:00Z"}}`,
	}
}

func TestIntegrationDiagnosticSchemasAcceptCanonicalFixtures(t *testing.T) {
	t.Parallel()

	validator := contracts.NewValidator(schemaRootDir(t))
	mustValidateFixtures(t, validator, integrationDiagnosticContractFixtures())
}
