package contracts_test

import (
	"testing"

	contracts "github.com/dopejs/dope-agent/daemon/internal/contracts"
)

func tenantIdentityContractFixtures() map[string]string {
	return map[string]string{
		"schemas/api/auth-access-token-resource.schema.json":           `{"tokenId":"tok_1","principalId":"prn_1","label":"web","mode":"local","tokenPreview":"dope_preview","status":"active","defaultTenantId":"ten_1","createdAt":"2026-04-24T10:00:00Z","updatedAt":"2026-04-24T10:00:00Z","lastUsedAt":"2026-04-24T10:01:00Z"}`,
		"schemas/api/tenant-resource.schema.json":                      `{"tenantId":"ten_1","tenantKind":"personal","displayName":"Personal tenant","status":"active","createdAt":"2026-04-24T10:00:00Z","updatedAt":"2026-04-24T10:00:00Z","createdByPrincipalId":"prn_1","defaultOwnerPrincipalId":"prn_1","callerMembershipRole":"owner","callerMembershipStatus":"active","callerPermissions":["tenant.manage","read_only.inspect"],"defaultForCurrentToken":true,"defaultForCurrentPrincipal":true}`,
		"schemas/api/principal-resource.schema.json":                   `{"principalId":"prn_1","principalKind":"local_operator","displayName":"Local operator","status":"active","defaultTenantId":"ten_1","createdAt":"2026-04-24T10:00:00Z","updatedAt":"2026-04-24T10:00:00Z"}`,
		"schemas/api/tenant-context-resource.schema.json":              `{"principalId":"prn_1","tokenId":"tok_1","tenantId":"ten_1","tenantSource":"default","membershipId":"mem_1","role":"owner","permissions":["tenant.manage","read_only.inspect"],"resolvedAt":"2026-04-24T10:01:00Z"}`,
		"schemas/api/tenant-permission-resource.schema.json":           `{"permission":"tenant.manage","allowed":true}`,
		"schemas/api/token-tenant-grant-resource.schema.json":          `{"grantId":"grant_1","tokenId":"tok_1","tenantId":"ten_1","isDefault":true,"status":"active","createdAt":"2026-04-24T10:00:00Z","updatedAt":"2026-04-24T10:00:00Z","grantedByPrincipalId":"prn_1"}`,
		"schemas/api/create-tenant.request.schema.json":                `{"displayName":"Acme","tenantKind":"organization"}`,
		"schemas/api/create-tenant.response.schema.json":               `{"tenant":{"tenantId":"ten_org","tenantKind":"organization","displayName":"Acme","status":"active","createdAt":"2026-04-24T10:00:00Z","updatedAt":"2026-04-24T10:00:00Z"},"membership":{"membershipId":"mem_owner","tenantId":"ten_org","principalId":"prn_1","role":"owner","status":"active","createdAt":"2026-04-24T10:00:00Z","updatedAt":"2026-04-24T10:00:00Z"}}`,
		"schemas/api/membership-resource.schema.json":                  `{"membershipId":"mem_1","tenantId":"ten_1","principalId":"prn_1","role":"owner","status":"active","createdAt":"2026-04-24T10:00:00Z","updatedAt":"2026-04-24T10:00:00Z","acceptedAt":"2026-04-24T10:00:00Z"}`,
		"schemas/api/membership-list.response.schema.json":             `{"items":[{"membershipId":"mem_1","tenantId":"ten_1","principalId":"prn_1","role":"owner","status":"active","createdAt":"2026-04-24T10:00:00Z","updatedAt":"2026-04-24T10:00:00Z"}]}`,
		"schemas/api/create-tenant-invitation.request.schema.json":     `{"invitedPrincipalId":"prn_2","role":"operator"}`,
		"schemas/api/tenant-invitation-resource.schema.json":           `{"invitationId":"inv_1","tenantId":"ten_1","invitedPrincipalId":"prn_2","invitedByPrincipalId":"prn_1","role":"operator","status":"invited","createdAt":"2026-04-24T10:00:00Z","updatedAt":"2026-04-24T10:00:00Z"}`,
		"schemas/api/create-tenant-invitation.response.schema.json":    `{"invitation":{"invitationId":"inv_1","tenantId":"ten_1","invitedPrincipalId":"prn_2","invitedByPrincipalId":"prn_1","role":"operator","status":"invited","createdAt":"2026-04-24T10:00:00Z","updatedAt":"2026-04-24T10:00:00Z"}}`,
		"schemas/api/tenant-invitation-list.response.schema.json":      `{"items":[{"invitationId":"inv_1","tenantId":"ten_1","invitedPrincipalId":"prn_2","invitedByPrincipalId":"prn_1","role":"operator","status":"invited","createdAt":"2026-04-24T10:00:00Z","updatedAt":"2026-04-24T10:00:00Z"}]}`,
		"schemas/api/accept-tenant-invitation.request.schema.json":     `{}`,
		"schemas/api/reject-tenant-invitation.request.schema.json":     `{}`,
		"schemas/api/tenant-invitation-decision.response.schema.json":  `{"membership":{"membershipId":"mem_2","tenantId":"ten_1","principalId":"prn_2","role":"operator","status":"active","invitationId":"inv_1","createdAt":"2026-04-24T10:00:00Z","updatedAt":"2026-04-24T10:00:00Z"}}`,
		"schemas/api/update-membership.request.schema.json":            `{"role":"viewer"}`,
		"schemas/api/principal-list.response.schema.json":              `{"items":[{"principalId":"prn_1","principalKind":"local_operator","displayName":"Local operator","status":"active","defaultTenantId":"ten_1","createdAt":"2026-04-24T10:00:00Z","updatedAt":"2026-04-24T10:00:00Z"}]}`,
		"schemas/api/update-principal.request.schema.json":             `{"status":"disabled"}`,
		"schemas/api/update-principal.response.schema.json":            `{"principal":{"principalId":"prn_1","principalKind":"local_operator","displayName":"Local operator","status":"disabled","defaultTenantId":"ten_1","createdAt":"2026-04-24T10:00:00Z","updatedAt":"2026-04-24T10:00:00Z"}}`,
		"schemas/api/tenant-audit-event-resource.schema.json":          `{"auditEventId":"audit_1","eventKind":"tenant.permission_denied","tenantId":"ten_1","principalId":"prn_1","tokenId":"tok_1","outcome":"denied","reasonCode":"permission_denied:tenant.manage","createdAt":"2026-04-24T10:00:00Z"}`,
		"schemas/api/tenant-audit-event-list.response.schema.json":     `{"items":[{"auditEventId":"audit_1","eventKind":"tenant.permission_denied","tenantId":"ten_1","principalId":"prn_1","tokenId":"tok_1","outcome":"denied","reasonCode":"permission_denied:tenant.manage","createdAt":"2026-04-24T10:00:00Z"}]}`,
		"schemas/api/auth-token-list.response.schema.json":             `{"items":[{"tokenId":"tok_1","principalId":"prn_1","label":"web","mode":"local","tokenPreview":"dope_preview","status":"active","defaultTenantId":"ten_1","createdAt":"2026-04-24T10:00:00Z","updatedAt":"2026-04-24T10:00:00Z"}]}`,
		"schemas/api/create-auth-token.request.schema.json":            `{"label":"automation","defaultTenantId":"ten_1","allowedTenantIds":["ten_1"]}`,
		"schemas/api/create-auth-token.response.schema.json":           `{"token":{"tokenId":"tok_2","principalId":"prn_1","label":"automation","mode":"token","tokenPreview":"dope_preview","status":"active","defaultTenantId":"ten_1","createdAt":"2026-04-24T10:00:00Z","updatedAt":"2026-04-24T10:00:00Z"},"accessToken":"dope_secret","grants":[{"grantId":"grant_2","tokenId":"tok_2","tenantId":"ten_1","isDefault":true,"status":"active","createdAt":"2026-04-24T10:00:00Z","updatedAt":"2026-04-24T10:00:00Z"}]}`,
		"schemas/api/rotate-auth-token.request.schema.json":            `{"reason":"scheduled"}`,
		"schemas/api/rotate-auth-token.response.schema.json":           `{"oldToken":{"tokenId":"tok_1","principalId":"prn_1","label":"web","mode":"local","tokenPreview":"dope_preview","status":"rotated","defaultTenantId":"ten_1","createdAt":"2026-04-24T10:00:00Z","updatedAt":"2026-04-24T10:00:00Z","rotatedToTokenId":"tok_2"},"newToken":{"tokenId":"tok_2","principalId":"prn_1","label":"web","mode":"local","tokenPreview":"dope_new","status":"active","defaultTenantId":"ten_1","createdAt":"2026-04-24T10:00:00Z","updatedAt":"2026-04-24T10:00:00Z","rotatedFromTokenId":"tok_1"},"accessToken":"dope_secret","grants":[{"grantId":"grant_2","tokenId":"tok_2","tenantId":"ten_1","isDefault":true,"status":"active","createdAt":"2026-04-24T10:00:00Z","updatedAt":"2026-04-24T10:00:00Z"}]}`,
		"schemas/api/revoke-auth-token.request.schema.json":            `{"reason":"manual"}`,
		"schemas/api/update-token-tenant-grants.request.schema.json":   `{"defaultTenantId":"ten_1","allowedTenantIds":["ten_1"],"reason":"least_privilege"}`,
		"schemas/api/update-token-tenant-grants.response.schema.json":  `{"tokenId":"tok_1","grants":[{"grantId":"grant_1","tokenId":"tok_1","tenantId":"ten_1","isDefault":true,"status":"active","createdAt":"2026-04-24T10:00:00Z","updatedAt":"2026-04-24T10:00:00Z"}]}`,
		"schemas/api/tenant-list.response.schema.json":                 `{"items":[{"tenantId":"ten_1","tenantKind":"personal","displayName":"Personal tenant","status":"active","createdAt":"2026-04-24T10:00:00Z","updatedAt":"2026-04-24T10:00:00Z","callerMembershipRole":"owner","callerMembershipStatus":"active","callerPermissions":["tenant.manage"],"defaultForCurrentToken":true,"defaultForCurrentPrincipal":true}]}`,
		"schemas/api/tenant-detail.response.schema.json":               `{"tenant":{"tenantId":"ten_1","tenantKind":"personal","displayName":"Personal tenant","status":"active","createdAt":"2026-04-24T10:00:00Z","updatedAt":"2026-04-24T10:00:00Z","callerMembershipRole":"owner","callerMembershipStatus":"active","callerPermissions":["tenant.manage"]},"tenantContext":{"principalId":"prn_1","tokenId":"tok_1","tenantId":"ten_1","tenantSource":"explicit_header","membershipId":"mem_1","role":"owner","permissions":["tenant.manage"],"resolvedAt":"2026-04-24T10:01:00Z"}}`,
		"schemas/api/auth-me.response.schema.json":                     `{"token":{"tokenId":"tok_1","principalId":"prn_1","label":"web","mode":"local","tokenPreview":"dope_preview","status":"active","defaultTenantId":"ten_1","createdAt":"2026-04-24T10:00:00Z","updatedAt":"2026-04-24T10:00:00Z"},"principal":{"principalId":"prn_1","principalKind":"local_operator","displayName":"Local operator","status":"active","defaultTenantId":"ten_1","createdAt":"2026-04-24T10:00:00Z","updatedAt":"2026-04-24T10:00:00Z"},"defaultTenant":{"tenantId":"ten_1","tenantKind":"personal","displayName":"Personal tenant","status":"active","createdAt":"2026-04-24T10:00:00Z","updatedAt":"2026-04-24T10:00:00Z","defaultForCurrentToken":true,"defaultForCurrentPrincipal":true},"currentTenant":{"tenantId":"ten_1","tenantKind":"personal","displayName":"Personal tenant","status":"active","createdAt":"2026-04-24T10:00:00Z","updatedAt":"2026-04-24T10:00:00Z","callerMembershipRole":"owner","callerMembershipStatus":"active","callerPermissions":["tenant.manage"]},"allowedTenants":[{"tenantId":"ten_1","tenantKind":"personal","displayName":"Personal tenant","status":"active","createdAt":"2026-04-24T10:00:00Z","updatedAt":"2026-04-24T10:00:00Z","defaultForCurrentToken":true,"defaultForCurrentPrincipal":true}],"tokenGrants":[{"grantId":"grant_1","tokenId":"tok_1","tenantId":"ten_1","isDefault":true,"status":"active","createdAt":"2026-04-24T10:00:00Z","updatedAt":"2026-04-24T10:00:00Z"}],"permissions":["tenant.manage"],"tenantContext":{"principalId":"prn_1","tokenId":"tok_1","tenantId":"ten_1","tenantSource":"default","membershipId":"mem_1","role":"owner","permissions":["tenant.manage"],"resolvedAt":"2026-04-24T10:01:00Z"}}`,
		"schemas/api/error-response.schema.json":                       `{"error":"tenant access denied","errorCode":"tenant_access_denied"}`,
		"schemas/events/tenant-access-denied.event.schema.json":        `{"eventId":"evt_tenant_1","sequence":1,"category":"tenant","name":"tenant.access_denied","occurredAt":"2026-04-24T10:01:00Z","scope":{},"resource":{"kind":"tenant","id":"ten_hidden"},"payload":{"principalId":"prn_1","tokenId":"tok_1","tenantId":"ten_hidden","reasonCode":"tenant_resolution_denied"}}`,
		"schemas/events/tenant-context-resolved.event.schema.json":     `{"eventId":"evt_tenant_2","sequence":2,"category":"tenant","name":"tenant.context_resolved","occurredAt":"2026-04-24T10:01:00Z","scope":{},"resource":{"kind":"tenant","id":"ten_1"},"payload":{"principalId":"prn_1","tokenId":"tok_1","tenantId":"ten_1","tenantSource":"default","membershipId":"mem_1","role":"owner"}}`,
		"schemas/events/tenant-membership-changed.event.schema.json":   `{"eventId":"evt_tenant_3","sequence":3,"category":"tenant","name":"tenant.membership_changed","occurredAt":"2026-04-24T10:01:00Z","scope":{},"resource":{"kind":"tenant","id":"ten_1"},"payload":{"tenantId":"ten_1","principalId":"prn_2","membershipId":"mem_2","role":"viewer","status":"active","reasonCode":"membership_role_updated"}}`,
		"schemas/events/tenant-invitation-created.event.schema.json":   `{"eventId":"evt_tenant_4","sequence":4,"category":"tenant","name":"tenant.invitation_created","occurredAt":"2026-04-24T10:01:00Z","scope":{},"resource":{"kind":"tenant","id":"ten_1"},"payload":{"tenantId":"ten_1","invitationId":"inv_1","invitedPrincipalId":"prn_2","role":"operator"}}`,
		"schemas/events/tenant-invitation-accepted.event.schema.json":  `{"eventId":"evt_tenant_5","sequence":5,"category":"tenant","name":"tenant.invitation_accepted","occurredAt":"2026-04-24T10:01:00Z","scope":{},"resource":{"kind":"tenant","id":"ten_1"},"payload":{"tenantId":"ten_1","invitationId":"inv_1","invitedPrincipalId":"prn_2","role":"operator"}}`,
		"schemas/events/tenant-invitation-rejected.event.schema.json":  `{"eventId":"evt_tenant_6","sequence":6,"category":"tenant","name":"tenant.invitation_rejected","occurredAt":"2026-04-24T10:01:00Z","scope":{},"resource":{"kind":"tenant","id":"ten_1"},"payload":{"tenantId":"ten_1","invitationId":"inv_1","invitedPrincipalId":"prn_2","role":"operator"}}`,
		"schemas/events/tenant-invitation-revoked.event.schema.json":   `{"eventId":"evt_tenant_7","sequence":7,"category":"tenant","name":"tenant.invitation_revoked","occurredAt":"2026-04-24T10:01:00Z","scope":{},"resource":{"kind":"tenant","id":"ten_1"},"payload":{"tenantId":"ten_1","invitationId":"inv_1","invitedPrincipalId":"prn_2","role":"operator"}}`,
		"schemas/events/tenant-invitation-expired.event.schema.json":   `{"eventId":"evt_tenant_8","sequence":8,"category":"tenant","name":"tenant.invitation_expired","occurredAt":"2026-04-24T10:01:00Z","scope":{},"resource":{"kind":"tenant","id":"ten_1"},"payload":{"tenantId":"ten_1","invitationId":"inv_1","invitedPrincipalId":"prn_2","role":"operator"}}`,
		"schemas/events/tenant-audit-failed-closed.event.schema.json":  `{"eventId":"evt_tenant_9","sequence":9,"category":"tenant","name":"tenant.audit_failed_closed","occurredAt":"2026-04-24T10:01:00Z","scope":{},"resource":{"kind":"tenant","id":"ten_1"},"payload":{"tenantId":"ten_1","principalId":"prn_1","tokenId":"tok_1","reasonCode":"audit_write_failed"}}`,
		"schemas/events/tenant-token-issued.event.schema.json":         `{"eventId":"evt_tenant_10","sequence":10,"category":"tenant","name":"tenant.token_issued","occurredAt":"2026-04-24T10:01:00Z","scope":{},"resource":{"kind":"token","id":"tok_2"},"payload":{"principalId":"prn_1","tokenId":"tok_2","defaultTenantId":"ten_1","allowedTenantIds":["ten_1"],"reasonCode":"token_issued"}}`,
		"schemas/events/tenant-token-rotated.event.schema.json":        `{"eventId":"evt_tenant_11","sequence":11,"category":"tenant","name":"tenant.token_rotated","occurredAt":"2026-04-24T10:01:00Z","scope":{},"resource":{"kind":"token","id":"tok_1"},"payload":{"principalId":"prn_1","oldTokenId":"tok_1","newTokenId":"tok_2","reasonCode":"scheduled"}}`,
		"schemas/events/tenant-token-revoked.event.schema.json":        `{"eventId":"evt_tenant_12","sequence":12,"category":"tenant","name":"tenant.token_revoked","occurredAt":"2026-04-24T10:01:00Z","scope":{},"resource":{"kind":"token","id":"tok_1"},"payload":{"principalId":"prn_1","tokenId":"tok_1","defaultTenantId":"ten_1","allowedTenantIds":["ten_1"],"reasonCode":"manual"}}`,
		"schemas/events/tenant-token-expiry-denied.event.schema.json":  `{"eventId":"evt_tenant_13","sequence":13,"category":"tenant","name":"tenant.token_expiry_denied","occurredAt":"2026-04-24T10:01:00Z","scope":{},"resource":{"kind":"token","id":"tok_1"},"payload":{"principalId":"prn_1","tokenId":"tok_1","defaultTenantId":"ten_1","allowedTenantIds":["ten_1"],"reasonCode":"token_expired"}}`,
		"schemas/events/tenant-token-grants-changed.event.schema.json": `{"eventId":"evt_tenant_14","sequence":14,"category":"tenant","name":"tenant.token_grants_changed","occurredAt":"2026-04-24T10:01:00Z","scope":{},"resource":{"kind":"token","id":"tok_1"},"payload":{"principalId":"prn_1","tokenId":"tok_1","defaultTenantId":"ten_1","allowedTenantIds":["ten_1"],"reasonCode":"token_grants_changed"}}`,
	}
}

func TestTenantIdentitySchemasAcceptCanonicalFixtures(t *testing.T) {
	t.Parallel()

	validator := contracts.NewValidator(schemaRootDir(t))
	mustValidateFixtures(t, validator, tenantIdentityContractFixtures())
}
