[package]
license.workspace = true
name = "kura-model-provider"
edition.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
kura-protocol.workspace = true
kura-llm.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
futures.workspace = true
reqwest.workspace = true
async-stream.workspace = true
bytes.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros", "rt-multi-thread"] }
