[package]
name = "dope-feishulark"
edition.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
dope-adapterrpc.workspace = true
dope-adapterprovider.workspace = true
dope-calendar.workspace = true
dope-mail.workspace = true
dope-integrations.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
ureq.workspace = true
