[package]
name = "kura-mail"
edition.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
kura-integrations.workspace = true
kura-livevalidation.workspace = true
kura-adapterrpc.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
thiserror.workspace = true
parking_lot.workspace = true
uuid = { workspace = true, features = ["v4"] }
