//! Schema migrations (port of the Go schemaMigrations list). Versions are added incrementally.

use crate::SchemaMigration;

#[must_use]
pub fn schema_migrations() -> Vec<SchemaMigration> {
    vec![
        SchemaMigration {
            version: 1,
            name: "baseline".to_string(),
            statements: vec![
                r#"CREATE TABLE IF NOT EXISTS schema_migrations (
                    version INTEGER PRIMARY KEY,
                    name TEXT NOT NULL,
                    applied_at TEXT NOT NULL
                );"#
                    .to_string(),
                r#"CREATE TABLE IF NOT EXISTS sessions (
                    session_id TEXT PRIMARY KEY,
                    kind TEXT NOT NULL,
                    status TEXT NOT NULL,
                    channel TEXT NOT NULL,
                    account_id TEXT,
                    peer_id TEXT NOT NULL,
                    thread_id TEXT,
                    routing_key TEXT NOT NULL UNIQUE,
                    generation INTEGER NOT NULL,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL,
                    last_active_at TEXT NOT NULL,
                    last_reset_at TEXT
                );"#
                    .to_string(),
                r#"CREATE TABLE IF NOT EXISTS auth_pairings (
                    pairing_id TEXT PRIMARY KEY,
                    mode TEXT NOT NULL,
                    label TEXT NOT NULL,
                    status TEXT NOT NULL,
                    code_hash TEXT NOT NULL,
                    code_preview TEXT,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL,
                    expires_at TEXT NOT NULL,
                    completed_at TEXT
                );"#
                    .to_string(),
                r#"CREATE TABLE IF NOT EXISTS auth_tokens (
                    token_id TEXT PRIMARY KEY,
                    label TEXT NOT NULL,
                    mode TEXT NOT NULL,
                    token_hash TEXT NOT NULL,
                    token_preview TEXT NOT NULL,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL,
                    last_used_at TEXT
                );"#
                    .to_string(),
                r#"CREATE TABLE IF NOT EXISTS approvals (
                    approval_id TEXT PRIMARY KEY,
                    action TEXT NOT NULL,
                    resource_kind TEXT,
                    resource_id TEXT,
                    reason TEXT NOT NULL,
                    requested_by TEXT,
                    status TEXT NOT NULL,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL,
                    resolved_at TEXT,
                    resolution TEXT,
                    comment TEXT
                );"#
                    .to_string(),
                r#"CREATE TABLE IF NOT EXISTS decisions (
                    decision_id TEXT PRIMARY KEY,
                    action TEXT NOT NULL,
                    resource_kind TEXT,
                    resource_id TEXT,
                    outcome TEXT NOT NULL,
                    reason TEXT NOT NULL,
                    approval_id TEXT,
                    created_at TEXT NOT NULL,
                    FOREIGN KEY(approval_id) REFERENCES approvals(approval_id) ON DELETE SET NULL
                );"#
                    .to_string(),
                r#"CREATE TABLE IF NOT EXISTS runs (
                    run_id TEXT PRIMARY KEY,
                    session_id TEXT,
                    entrypoint TEXT NOT NULL,
                    status TEXT NOT NULL,
                    goal TEXT NOT NULL,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL,
                    FOREIGN KEY(session_id) REFERENCES sessions(session_id) ON DELETE SET NULL
                );"#
                    .to_string(),
                r#"CREATE TABLE IF NOT EXISTS connectors (
                    connector_id TEXT PRIMARY KEY,
                    kind TEXT NOT NULL,
                    display_name TEXT NOT NULL,
                    status TEXT NOT NULL,
                    failure_count INTEGER NOT NULL,
                    restart_count INTEGER NOT NULL,
                    backoff_seconds INTEGER NOT NULL,
                    next_restart_at TEXT,
                    last_restart_at TEXT,
                    last_heartbeat_at TEXT,
                    last_failure_reason TEXT,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL
                );"#
                    .to_string(),
                r#"CREATE TABLE IF NOT EXISTS capabilities (
                    capability_id TEXT PRIMARY KEY,
                    kind TEXT NOT NULL,
                    display_name TEXT NOT NULL,
                    status TEXT NOT NULL,
                    failure_count INTEGER NOT NULL,
                    restart_count INTEGER NOT NULL,
                    backoff_seconds INTEGER NOT NULL,
                    next_restart_at TEXT,
                    last_restart_at TEXT,
                    last_heartbeat_at TEXT,
                    last_failure_reason TEXT,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL
                );"#
                    .to_string(),
                r#"CREATE TABLE IF NOT EXISTS steps (
                    step_id TEXT PRIMARY KEY,
                    run_id TEXT NOT NULL,
                    title TEXT NOT NULL,
                    kind TEXT NOT NULL,
                    status TEXT NOT NULL,
                    input_json TEXT,
                    output_json TEXT,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL,
                    FOREIGN KEY(run_id) REFERENCES runs(run_id) ON DELETE CASCADE
                );"#
                    .to_string(),
                r#"CREATE TABLE IF NOT EXISTS tool_calls (
                    tool_call_id TEXT PRIMARY KEY,
                    run_id TEXT NOT NULL,
                    step_id TEXT NOT NULL,
                    capability_id TEXT NOT NULL,
                    tool_name TEXT NOT NULL,
                    status TEXT NOT NULL,
                    input_json TEXT,
                    output_json TEXT,
                    error_text TEXT,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL,
                    FOREIGN KEY(run_id) REFERENCES runs(run_id) ON DELETE CASCADE,
                    FOREIGN KEY(step_id) REFERENCES steps(step_id) ON DELETE CASCADE
                );"#
                    .to_string(),
                r#"CREATE TABLE IF NOT EXISTS llm_dispatches (
                    dispatch_id TEXT PRIMARY KEY,
                    provider TEXT NOT NULL,
                    model TEXT NOT NULL,
                    messages_json TEXT NOT NULL,
                    stream INTEGER NOT NULL,
                    status TEXT NOT NULL,
                    output_text TEXT NOT NULL,
                    finish_reason TEXT,
                    usage_json TEXT NOT NULL,
                    error_code TEXT,
                    error_text TEXT,
                    timeout_ms INTEGER NOT NULL,
                    max_retries INTEGER NOT NULL,
                    attempt_count INTEGER NOT NULL,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL,
                    started_at TEXT,
                    completed_at TEXT
                );"#
                    .to_string(),
                r#"CREATE TABLE IF NOT EXISTS events (
                    event_id TEXT PRIMARY KEY,
                    category TEXT NOT NULL,
                    name TEXT NOT NULL,
                    occurred_at TEXT NOT NULL,
                    session_id TEXT,
                    run_id TEXT,
                    step_id TEXT,
                    connector_id TEXT,
                    capability_id TEXT,
                    resource_kind TEXT NOT NULL,
                    resource_id TEXT NOT NULL,
                    payload_json TEXT
                );"#
                    .to_string(),
                r#"CREATE TABLE IF NOT EXISTS checkpoints (
                    checkpoint_id TEXT PRIMARY KEY,
                    run_id TEXT NOT NULL,
                    captured_at TEXT NOT NULL,
                    snapshot_json TEXT NOT NULL,
                    FOREIGN KEY(run_id) REFERENCES runs(run_id) ON DELETE CASCADE
                );"#
                    .to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_steps_run_id ON steps(run_id);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_connectors_kind_status ON connectors(kind, status);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_capabilities_kind_status ON capabilities(kind, status);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_tool_calls_run_step ON tool_calls(run_id, step_id, created_at);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_llm_dispatches_provider_status ON llm_dispatches(provider, status, created_at);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_approvals_status_created ON approvals(status, created_at);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_sessions_channel_peer ON sessions(channel, peer_id, thread_id);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_events_run_id ON events(run_id, occurred_at);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_events_session_id ON events(session_id, occurred_at);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_events_category ON events(category, occurred_at);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_checkpoints_run_id ON checkpoints(run_id, captured_at);"#.to_string(),
            ],
        },
        SchemaMigration {
            version: 2,
            name: "operational_indexes".to_string(),
            statements: vec![
                r#"CREATE INDEX IF NOT EXISTS idx_events_resource_scope ON events(resource_kind, resource_id, occurred_at);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_tool_calls_capability_created ON tool_calls(capability_id, created_at);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_auth_tokens_last_used_at ON auth_tokens(last_used_at);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_decisions_approval_id ON decisions(approval_id, created_at);"#.to_string(),
            ],
        },
        SchemaMigration {
            version: 3,
            name: "provider_checks".to_string(),
            statements: vec![
                r#"CREATE TABLE IF NOT EXISTS provider_checks (
                    check_id TEXT PRIMARY KEY,
                    provider_id TEXT NOT NULL,
                    family TEXT NOT NULL,
                    auth_mode TEXT NOT NULL,
                    status TEXT NOT NULL,
                    model TEXT NOT NULL,
                    endpoint TEXT,
                    error_class TEXT,
                    error_code TEXT,
                    error_message TEXT,
                    usage_json TEXT NOT NULL,
                    created_at TEXT NOT NULL,
                    completed_at TEXT NOT NULL
                );"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_provider_checks_provider_created ON provider_checks(provider_id, created_at DESC, check_id DESC);"#.to_string(),
            ],
        },
        SchemaMigration {
            version: 4,
            name: "managed_provider_state".to_string(),
            statements: vec![
                r#"CREATE TABLE IF NOT EXISTS provider_auth_states (
                    provider_id TEXT PRIMARY KEY,
                    family TEXT NOT NULL,
                    auth_mode TEXT NOT NULL,
                    status TEXT NOT NULL,
                    cli_path TEXT,
                    cli_available INTEGER NOT NULL,
                    account_label TEXT,
                    account_id TEXT,
                    plan TEXT,
                    auth_method TEXT,
                    login_command_json TEXT NOT NULL,
                    logout_command_json TEXT NOT NULL,
                    last_checked_at TEXT NOT NULL,
                    last_authenticated_at TEXT,
                    last_error TEXT,
                    metadata_json TEXT NOT NULL
                );"#.to_string(),
                r#"CREATE TABLE IF NOT EXISTS provider_models (
                    provider_id TEXT NOT NULL,
                    model_id TEXT NOT NULL,
                    display_name TEXT NOT NULL,
                    description TEXT,
                    default_flag INTEGER NOT NULL,
                    available_flag INTEGER NOT NULL,
                    source TEXT NOT NULL,
                    chat INTEGER NOT NULL,
                    stream INTEGER NOT NULL,
                    coding INTEGER NOT NULL,
                    tool_use INTEGER NOT NULL,
                    reasoning_levels_json TEXT NOT NULL,
                    PRIMARY KEY (provider_id, model_id)
                );"#.to_string(),
                r#"CREATE TABLE IF NOT EXISTS provider_preferences (
                    provider_id TEXT PRIMARY KEY,
                    default_model TEXT NOT NULL,
                    updated_at TEXT NOT NULL
                );"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_provider_models_provider ON provider_models(provider_id, model_id);"#.to_string(),
            ],
        },
        SchemaMigration {
            version: 5,
            name: "connector_messages".to_string(),
            statements: vec![
                r#"CREATE TABLE IF NOT EXISTS connector_messages (
                    delivery_id TEXT PRIMARY KEY,
                    connector_id TEXT NOT NULL,
                    direction TEXT NOT NULL,
                    external_message_id TEXT,
                    session_id TEXT,
                    run_id TEXT,
                    channel_id TEXT NOT NULL,
                    peer_id TEXT,
                    thread_id TEXT,
                    author_id TEXT,
                    content TEXT NOT NULL,
                    status TEXT NOT NULL,
                    error_text TEXT,
                    reply_to_external_message_id TEXT,
                    response_to_delivery_id TEXT,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL,
                    FOREIGN KEY(session_id) REFERENCES sessions(session_id) ON DELETE SET NULL,
                    FOREIGN KEY(run_id) REFERENCES runs(run_id) ON DELETE SET NULL
                );"#.to_string(),
                r#"CREATE UNIQUE INDEX IF NOT EXISTS idx_connector_messages_external ON connector_messages(connector_id, direction, external_message_id) WHERE external_message_id IS NOT NULL;"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_connector_messages_connector_created ON connector_messages(connector_id, created_at DESC, delivery_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_connector_messages_session_created ON connector_messages(session_id, created_at DESC, delivery_id DESC);"#.to_string(),
            ],
        },
        SchemaMigration {
            version: 6,
            name: "sandbox_execution_plane".to_string(),
            statements: vec![
                r#"CREATE TABLE IF NOT EXISTS sandbox_executions (
                    execution_id TEXT PRIMARY KEY,
                    profile_id TEXT NOT NULL,
                    backend_kind TEXT NOT NULL,
                    status TEXT NOT NULL,
                    approval_id TEXT,
                    requested_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL,
                    started_at TEXT,
                    completed_at TEXT,
                    document_json TEXT NOT NULL,
                    FOREIGN KEY(approval_id) REFERENCES approvals(approval_id) ON DELETE SET NULL
                );"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_sandbox_executions_status_requested ON sandbox_executions(status, requested_at DESC, execution_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_sandbox_executions_profile_requested ON sandbox_executions(profile_id, requested_at DESC, execution_id DESC);"#.to_string(),
            ],
        },
        SchemaMigration {
            version: 7,
            name: "sandbox_requirement_contract".to_string(),
            statements: vec![
                r#"ALTER TABLE provider_auth_states ADD COLUMN sandbox_json TEXT;"#.to_string(),
                r#"ALTER TABLE tool_calls ADD COLUMN sandbox_json TEXT;"#.to_string(),
                r#"CREATE TABLE IF NOT EXISTS consumer_policy_records (
                    policy_record_id TEXT PRIMARY KEY,
                    consumer_kind TEXT NOT NULL,
                    consumer_id TEXT NOT NULL,
                    operation_kind TEXT NOT NULL,
                    declaration_id TEXT,
                    status TEXT NOT NULL,
                    decision TEXT NOT NULL,
                    approval_status TEXT NOT NULL,
                    secret_resolution TEXT NOT NULL,
                    requested_by TEXT,
                    sandbox_execution_id TEXT,
                    tool_call_id TEXT,
                    provider_operation_id TEXT,
                    started_at TEXT NOT NULL,
                    completed_at TEXT,
                    document_json TEXT NOT NULL
                );"#.to_string(),
                r#"CREATE TABLE IF NOT EXISTS secret_scope_bindings (
                    binding_id TEXT PRIMARY KEY,
                    consumer_kind TEXT NOT NULL,
                    consumer_id TEXT NOT NULL,
                    environment_scope TEXT NOT NULL,
                    secret_ref TEXT NOT NULL,
                    default_source TEXT NOT NULL,
                    delivery_kind TEXT NOT NULL,
                    active INTEGER NOT NULL,
                    document_json TEXT NOT NULL
                );"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_policy_records_consumer_started ON consumer_policy_records(consumer_kind, consumer_id, started_at DESC, policy_record_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_policy_records_status_started ON consumer_policy_records(status, started_at DESC, policy_record_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_secret_scope_bindings_consumer_secret ON secret_scope_bindings(consumer_kind, consumer_id, secret_ref);"#.to_string(),
            ],
        },
        SchemaMigration {
            version: 8,
            name: "mcp_execution_plane".to_string(),
            statements: vec![
                r#"CREATE TABLE IF NOT EXISTS mcp_servers (
                    server_id TEXT PRIMARY KEY,
                    enabled INTEGER NOT NULL,
                    updated_at TEXT NOT NULL,
                    document_json TEXT NOT NULL
                );"#.to_string(),
                r#"CREATE TABLE IF NOT EXISTS mcp_server_states (
                    server_id TEXT PRIMARY KEY,
                    status TEXT NOT NULL,
                    updated_at TEXT NOT NULL,
                    document_json TEXT NOT NULL,
                    FOREIGN KEY(server_id) REFERENCES mcp_servers(server_id) ON DELETE CASCADE
                );"#.to_string(),
                r#"CREATE TABLE IF NOT EXISTS mcp_tools (
                    server_id TEXT NOT NULL,
                    tool_name TEXT NOT NULL,
                    discovery_status TEXT NOT NULL,
                    updated_at TEXT NOT NULL,
                    last_discovered_at TEXT,
                    document_json TEXT NOT NULL,
                    PRIMARY KEY (server_id, tool_name),
                    FOREIGN KEY(server_id) REFERENCES mcp_servers(server_id) ON DELETE CASCADE
                );"#.to_string(),
                r#"CREATE TABLE IF NOT EXISTS mcp_tool_exposure_rules (
                    server_id TEXT NOT NULL,
                    tool_name TEXT NOT NULL,
                    runtime_surface TEXT NOT NULL,
                    exposure_mode TEXT NOT NULL,
                    active INTEGER NOT NULL,
                    updated_at TEXT NOT NULL,
                    document_json TEXT NOT NULL,
                    PRIMARY KEY (server_id, tool_name, runtime_surface),
                    FOREIGN KEY(server_id, tool_name) REFERENCES mcp_tools(server_id, tool_name) ON DELETE CASCADE
                );"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_mcp_servers_enabled ON mcp_servers(enabled, updated_at DESC, server_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_mcp_server_states_status ON mcp_server_states(status, updated_at DESC, server_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_mcp_tools_server_status ON mcp_tools(server_id, discovery_status, tool_name);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_mcp_tool_exposure_surface ON mcp_tool_exposure_rules(runtime_surface, exposure_mode, server_id, tool_name);"#.to_string(),
            ],
        },
        SchemaMigration {
            version: 9,
            name: "skill_tool_sandbox_execution".to_string(),
            statements: vec![
                r#"ALTER TABLE tool_calls ADD COLUMN invocation_kind TEXT;"#.to_string(),
                r#"ALTER TABLE tool_calls ADD COLUMN skill_id TEXT;"#.to_string(),
                r#"ALTER TABLE tool_calls ADD COLUMN sandbox_execution_id TEXT;"#.to_string(),
                r#"ALTER TABLE tool_calls ADD COLUMN failure_class TEXT;"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_tool_calls_run_step_created ON tool_calls(run_id, step_id, created_at DESC, tool_call_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_tool_calls_skill_created ON tool_calls(skill_id, created_at DESC, tool_call_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_tool_calls_sandbox_execution ON tool_calls(sandbox_execution_id);"#.to_string(),
            ],
        },
        SchemaMigration {
            version: 10,
            name: "mcp_runtime_catalog".to_string(),
            statements: vec![
                r#"ALTER TABLE tool_calls ADD COLUMN mcp_server_id TEXT;"#.to_string(),
                r#"ALTER TABLE tool_calls ADD COLUMN mcp_server_name TEXT;"#.to_string(),
                r#"ALTER TABLE tool_calls ADD COLUMN mcp_tool_name TEXT;"#.to_string(),
                r#"ALTER TABLE tool_calls ADD COLUMN mcp_transport_kind TEXT;"#.to_string(),
                r#"ALTER TABLE tool_calls ADD COLUMN mcp_session_id TEXT;"#.to_string(),
                r#"ALTER TABLE tool_calls ADD COLUMN authorization_result TEXT;"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_tool_calls_mcp_server_created ON tool_calls(mcp_server_id, created_at DESC, tool_call_id DESC);"#.to_string(),
            ],
        },
        SchemaMigration {
            version: 11,
            name: "workflow_orchestration".to_string(),
            statements: vec![
                r#"CREATE TABLE IF NOT EXISTS workflows (
                    workflow_id TEXT PRIMARY KEY,
                    run_id TEXT NOT NULL,
                    environment_scope TEXT NOT NULL,
                    goal TEXT NOT NULL,
                    status TEXT NOT NULL,
                    plan_summary TEXT,
                    failure_summary TEXT,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL,
                    started_at TEXT,
                    completed_at TEXT,
                    interrupted_at TEXT,
                    document_json TEXT NOT NULL,
                    FOREIGN KEY(run_id) REFERENCES runs(run_id) ON DELETE CASCADE
                );"#.to_string(),
                r#"CREATE TABLE IF NOT EXISTS workflow_steps (
                    workflow_step_id TEXT PRIMARY KEY,
                    workflow_id TEXT NOT NULL,
                    position INTEGER NOT NULL,
                    status TEXT NOT NULL,
                    runtime_step_id TEXT,
                    active_tool_call_id TEXT,
                    attempt_count INTEGER NOT NULL,
                    max_attempts INTEGER NOT NULL,
                    last_failure_class TEXT,
                    blocked_reason TEXT,
                    document_json TEXT NOT NULL,
                    FOREIGN KEY(workflow_id) REFERENCES workflows(workflow_id) ON DELETE CASCADE
                );"#.to_string(),
                r#"CREATE TABLE IF NOT EXISTS workflow_dependencies (
                    dependency_id TEXT PRIMARY KEY,
                    workflow_id TEXT NOT NULL,
                    document_json TEXT NOT NULL,
                    FOREIGN KEY(workflow_id) REFERENCES workflows(workflow_id) ON DELETE CASCADE
                );"#.to_string(),
                r#"CREATE TABLE IF NOT EXISTS workflow_handoffs (
                    handoff_id TEXT PRIMARY KEY,
                    workflow_id TEXT NOT NULL,
                    status TEXT NOT NULL,
                    document_json TEXT NOT NULL,
                    FOREIGN KEY(workflow_id) REFERENCES workflows(workflow_id) ON DELETE CASCADE
                );"#.to_string(),
                r#"ALTER TABLE steps ADD COLUMN workflow_id TEXT;"#.to_string(),
                r#"ALTER TABLE steps ADD COLUMN workflow_step_id TEXT;"#.to_string(),
                r#"ALTER TABLE steps ADD COLUMN attempt INTEGER NOT NULL DEFAULT 0;"#.to_string(),
                r#"ALTER TABLE tool_calls ADD COLUMN workflow_id TEXT;"#.to_string(),
                r#"ALTER TABLE tool_calls ADD COLUMN workflow_step_id TEXT;"#.to_string(),
                r#"ALTER TABLE tool_calls ADD COLUMN attempt INTEGER NOT NULL DEFAULT 0;"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_workflows_run_env_created ON workflows(run_id, environment_scope, created_at DESC, workflow_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_workflow_steps_workflow_position ON workflow_steps(workflow_id, position ASC, workflow_step_id ASC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_steps_workflow_linkage ON steps(workflow_id, workflow_step_id, attempt);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_tool_calls_workflow_linkage ON tool_calls(workflow_id, workflow_step_id, attempt, created_at DESC, tool_call_id DESC);"#.to_string(),
            ],
        },
        SchemaMigration {
            version: 12,
            name: "scheduled_tasks_wakeups".to_string(),
            statements: vec![
                r#"CREATE TABLE IF NOT EXISTS schedules (
                    schedule_id TEXT PRIMARY KEY,
                    environment_scope TEXT NOT NULL,
                    kind TEXT NOT NULL,
                    status TEXT NOT NULL,
                    target_ref_id TEXT NOT NULL,
                    timezone TEXT,
                    next_due_at TEXT,
                    last_attempt_at TEXT,
                    last_outcome TEXT,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL,
                    paused_at TEXT,
                    cancelled_at TEXT,
                    completed_at TEXT,
                    document_json TEXT NOT NULL
                );"#.to_string(),
                r#"CREATE TABLE IF NOT EXISTS schedule_targets (
                    target_ref_id TEXT PRIMARY KEY,
                    schedule_id TEXT NOT NULL,
                    target_kind TEXT NOT NULL,
                    revision INTEGER NOT NULL,
                    active INTEGER NOT NULL,
                    updated_at TEXT NOT NULL,
                    document_json TEXT NOT NULL,
                    FOREIGN KEY(schedule_id) REFERENCES schedules(schedule_id) ON DELETE CASCADE
                );"#.to_string(),
                r#"CREATE TABLE IF NOT EXISTS schedule_dispatch_attempts (
                    attempt_id TEXT PRIMARY KEY,
                    schedule_id TEXT NOT NULL,
                    due_at TEXT NOT NULL,
                    trigger_source TEXT NOT NULL,
                    dispatch_status TEXT NOT NULL,
                    failure_class TEXT,
                    failure_reason TEXT,
                    retry_count INTEGER NOT NULL,
                    retry_budget INTEGER NOT NULL,
                    next_retry_at TEXT,
                    resolved_target_revision INTEGER NOT NULL,
                    run_id TEXT,
                    workflow_id TEXT,
                    downstream_status TEXT NOT NULL,
                    skipped_reason TEXT,
                    missed_count INTEGER NOT NULL,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL,
                    document_json TEXT NOT NULL,
                    FOREIGN KEY(schedule_id) REFERENCES schedules(schedule_id) ON DELETE CASCADE
                );"#.to_string(),
                r#"ALTER TABLE runs ADD COLUMN schedule_id TEXT;"#.to_string(),
                r#"ALTER TABLE runs ADD COLUMN schedule_attempt_id TEXT;"#.to_string(),
                r#"ALTER TABLE workflows ADD COLUMN schedule_id TEXT;"#.to_string(),
                r#"ALTER TABLE workflows ADD COLUMN schedule_attempt_id TEXT;"#.to_string(),
                r#"ALTER TABLE events ADD COLUMN workflow_id TEXT;"#.to_string(),
                r#"ALTER TABLE events ADD COLUMN workflow_step_id TEXT;"#.to_string(),
                r#"ALTER TABLE events ADD COLUMN schedule_id TEXT;"#.to_string(),
                r#"ALTER TABLE events ADD COLUMN schedule_attempt_id TEXT;"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_schedules_env_status_due ON schedules(environment_scope, status, next_due_at, schedule_id);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_schedule_targets_schedule ON schedule_targets(schedule_id, updated_at DESC, target_ref_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_schedule_attempts_schedule_due ON schedule_dispatch_attempts(schedule_id, due_at DESC, attempt_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_schedule_attempts_retry_due ON schedule_dispatch_attempts(dispatch_status, next_retry_at, schedule_id);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_runs_schedule_linkage ON runs(schedule_id, schedule_attempt_id, created_at DESC, run_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_workflows_schedule_linkage ON workflows(schedule_id, schedule_attempt_id, created_at DESC, workflow_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_events_schedule_id ON events(schedule_id, occurred_at);"#.to_string(),
            ],
        },
        SchemaMigration {
            version: 13,
            name: "event_environment_scope".to_string(),
            statements: vec![
                r#"ALTER TABLE events ADD COLUMN environment_scope TEXT NOT NULL DEFAULT '';"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_events_env_category ON events(environment_scope, category, occurred_at);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_events_env_schedule ON events(environment_scope, schedule_id, occurred_at);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_events_env_run ON events(environment_scope, run_id, occurred_at);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_events_env_session ON events(environment_scope, session_id, occurred_at);"#.to_string(),
            ],
        },
        SchemaMigration {
            version: 14,
            name: "computer_use_capability_plane".to_string(),
            statements: vec![
                r#"CREATE TABLE IF NOT EXISTS computer_use_sessions (
                    computer_use_session_id TEXT PRIMARY KEY,
                    environment_scope TEXT NOT NULL,
                    run_id TEXT NOT NULL,
                    workflow_id TEXT,
                    workflow_step_id TEXT,
                    status TEXT NOT NULL,
                    driver_kind TEXT NOT NULL,
                    trusted_page_scope_json TEXT,
                    current_page_json TEXT,
                    last_action_id TEXT,
                    started_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL,
                    closed_at TEXT,
                    interrupted_at TEXT,
                    document_json TEXT NOT NULL,
                    FOREIGN KEY(run_id) REFERENCES runs(run_id) ON DELETE CASCADE
                );"#.to_string(),
                r#"CREATE TABLE IF NOT EXISTS computer_use_actions (
                    computer_use_action_id TEXT PRIMARY KEY,
                    environment_scope TEXT NOT NULL,
                    computer_use_session_id TEXT NOT NULL,
                    run_id TEXT NOT NULL,
                    step_id TEXT,
                    tool_call_id TEXT,
                    workflow_id TEXT,
                    workflow_step_id TEXT,
                    action_kind TEXT NOT NULL,
                    status TEXT NOT NULL,
                    risk_level TEXT NOT NULL,
                    approval_id TEXT,
                    target_match_context_json TEXT,
                    page_before_json TEXT,
                    page_after_json TEXT,
                    failure_class TEXT,
                    failure_reason TEXT,
                    requested_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL,
                    completed_at TEXT,
                    input_json TEXT,
                    document_json TEXT NOT NULL,
                    FOREIGN KEY(computer_use_session_id) REFERENCES computer_use_sessions(computer_use_session_id) ON DELETE CASCADE,
                    FOREIGN KEY(run_id) REFERENCES runs(run_id) ON DELETE CASCADE
                );"#.to_string(),
                r#"CREATE TABLE IF NOT EXISTS computer_use_artifacts (
                    artifact_id TEXT PRIMARY KEY,
                    environment_scope TEXT NOT NULL,
                    computer_use_session_id TEXT NOT NULL,
                    computer_use_action_id TEXT NOT NULL,
                    run_id TEXT NOT NULL,
                    kind TEXT NOT NULL,
                    status TEXT NOT NULL,
                    mime_type TEXT,
                    file_name TEXT,
                    byte_size INTEGER NOT NULL,
                    storage_key TEXT,
                    sha256 TEXT,
                    capture_failure_reason TEXT,
                    created_at TEXT NOT NULL,
                    available_at TEXT,
                    document_json TEXT NOT NULL,
                    FOREIGN KEY(computer_use_session_id) REFERENCES computer_use_sessions(computer_use_session_id) ON DELETE CASCADE,
                    FOREIGN KEY(computer_use_action_id) REFERENCES computer_use_actions(computer_use_action_id) ON DELETE CASCADE,
                    FOREIGN KEY(run_id) REFERENCES runs(run_id) ON DELETE CASCADE
                );"#.to_string(),
                r#"ALTER TABLE tool_calls ADD COLUMN computer_use_session_id TEXT;"#.to_string(),
                r#"ALTER TABLE tool_calls ADD COLUMN computer_use_action_id TEXT;"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_computer_use_sessions_run ON computer_use_sessions(environment_scope, run_id, updated_at DESC, computer_use_session_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_computer_use_actions_session ON computer_use_actions(environment_scope, computer_use_session_id, requested_at ASC, computer_use_action_id ASC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_computer_use_actions_approval ON computer_use_actions(environment_scope, approval_id, requested_at DESC, computer_use_action_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_computer_use_artifacts_action ON computer_use_artifacts(environment_scope, computer_use_action_id, created_at ASC, artifact_id ASC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_tool_calls_computer_use_session ON tool_calls(computer_use_session_id, created_at DESC, tool_call_id DESC);"#.to_string(),
            ],
        },
        SchemaMigration {
            version: 15,
            name: "personal_integrations_platform".to_string(),
            statements: vec![
                r#"CREATE TABLE IF NOT EXISTS integrations (
                    integration_id TEXT PRIMARY KEY,
                    domain_kind TEXT NOT NULL,
                    environment_scope TEXT NOT NULL,
                    account_key TEXT,
                    backend_kind TEXT NOT NULL,
                    readiness_status TEXT NOT NULL,
                    canonical_default INTEGER NOT NULL,
                    updated_at TEXT NOT NULL,
                    document_json TEXT NOT NULL
                );"#.to_string(),
                r#"ALTER TABLE approvals ADD COLUMN integration_bindings_json TEXT;"#.to_string(),
                r#"ALTER TABLE tool_calls ADD COLUMN integration_bindings_json TEXT;"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_integrations_env_domain_account ON integrations(environment_scope, domain_kind, account_key, canonical_default);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_integrations_readiness ON integrations(environment_scope, readiness_status, updated_at DESC, integration_id DESC);"#.to_string(),
            ],
        },
        SchemaMigration {
            version: 16,
            name: "delivery_plane".to_string(),
            statements: vec![
                r#"CREATE TABLE IF NOT EXISTS delivery_targets (
                    target_id TEXT PRIMARY KEY,
                    environment_scope TEXT NOT NULL,
                    target_kind TEXT NOT NULL,
                    status TEXT NOT NULL,
                    updated_at TEXT NOT NULL,
                    document_json TEXT NOT NULL
                );"#.to_string(),
                r#"CREATE TABLE IF NOT EXISTS delivery_preferences (
                    preference_id TEXT PRIMARY KEY,
                    environment_scope TEXT NOT NULL,
                    scope_kind TEXT NOT NULL,
                    integration_id TEXT,
                    active INTEGER NOT NULL,
                    updated_at TEXT NOT NULL,
                    document_json TEXT NOT NULL
                );"#.to_string(),
                r#"CREATE TABLE IF NOT EXISTS delivery_outcomes (
                    delivery_id TEXT PRIMARY KEY,
                    environment_scope TEXT NOT NULL,
                    source_kind TEXT NOT NULL,
                    source_id TEXT NOT NULL,
                    run_id TEXT,
                    workflow_id TEXT,
                    schedule_id TEXT,
                    integration_id TEXT,
                    status TEXT NOT NULL,
                    chosen_target_id TEXT,
                    preference_id TEXT,
                    summary_window_id TEXT,
                    updated_at TEXT NOT NULL,
                    document_json TEXT NOT NULL
                );"#.to_string(),
                r#"CREATE TABLE IF NOT EXISTS delivery_attempts (
                    attempt_id TEXT PRIMARY KEY,
                    delivery_id TEXT NOT NULL,
                    attempt_number INTEGER NOT NULL,
                    target_id TEXT NOT NULL,
                    status TEXT NOT NULL,
                    next_retry_at TEXT,
                    document_json TEXT NOT NULL,
                    FOREIGN KEY(delivery_id) REFERENCES delivery_outcomes(delivery_id) ON DELETE CASCADE
                );"#.to_string(),
                r#"CREATE TABLE IF NOT EXISTS delivery_summary_windows (
                    summary_window_id TEXT PRIMARY KEY,
                    environment_scope TEXT NOT NULL,
                    target_id TEXT NOT NULL,
                    preference_id TEXT NOT NULL,
                    status TEXT NOT NULL,
                    window_ends_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL,
                    document_json TEXT NOT NULL
                );"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_delivery_targets_env_status ON delivery_targets(environment_scope, status, updated_at DESC, target_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_delivery_preferences_env_scope ON delivery_preferences(environment_scope, scope_kind, integration_id, active, updated_at DESC, preference_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_delivery_outcomes_env_source ON delivery_outcomes(environment_scope, source_kind, source_id, updated_at DESC, delivery_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_delivery_outcomes_env_run ON delivery_outcomes(environment_scope, run_id, updated_at DESC, delivery_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_delivery_outcomes_env_workflow ON delivery_outcomes(environment_scope, workflow_id, updated_at DESC, delivery_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_delivery_outcomes_env_schedule ON delivery_outcomes(environment_scope, schedule_id, updated_at DESC, delivery_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_delivery_outcomes_env_target ON delivery_outcomes(environment_scope, chosen_target_id, updated_at DESC, delivery_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_delivery_attempts_delivery ON delivery_attempts(delivery_id, attempt_number ASC, attempt_id ASC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_delivery_summary_windows_env_status ON delivery_summary_windows(environment_scope, status, window_ends_at ASC, summary_window_id ASC);"#.to_string(),
            ],
        },
        SchemaMigration {
            version: 17,
            name: "calendar_domain".to_string(),
            statements: vec![
                r#"CREATE TABLE IF NOT EXISTS calendar_accounts (
                    calendar_account_id TEXT PRIMARY KEY,
                    integration_id TEXT NOT NULL UNIQUE,
                    environment_scope TEXT NOT NULL,
                    account_key TEXT,
                    readiness_status TEXT NOT NULL,
                    canonical_default INTEGER NOT NULL,
                    updated_at TEXT NOT NULL,
                    document_json TEXT NOT NULL
                );"#.to_string(),
                r#"CREATE TABLE IF NOT EXISTS calendar_operations (
                    operation_id TEXT PRIMARY KEY,
                    integration_id TEXT NOT NULL,
                    calendar_account_id TEXT NOT NULL,
                    environment_scope TEXT NOT NULL,
                    operation_class TEXT NOT NULL,
                    status TEXT NOT NULL,
                    external_event_id TEXT,
                    run_id TEXT,
                    workflow_id TEXT,
                    schedule_id TEXT,
                    delivery_id TEXT,
                    updated_at TEXT NOT NULL,
                    document_json TEXT NOT NULL
                );"#.to_string(),
                r#"CREATE TABLE IF NOT EXISTS calendar_artifacts (
                    artifact_id TEXT PRIMARY KEY,
                    operation_id TEXT NOT NULL,
                    integration_id TEXT NOT NULL,
                    environment_scope TEXT NOT NULL,
                    kind TEXT NOT NULL,
                    external_event_id TEXT,
                    created_at TEXT NOT NULL,
                    document_json TEXT NOT NULL
                );"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_calendar_accounts_env_readiness ON calendar_accounts(environment_scope, readiness_status, updated_at DESC, integration_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_calendar_accounts_env_default ON calendar_accounts(environment_scope, account_key, canonical_default, updated_at DESC, integration_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_calendar_operations_env_class_status ON calendar_operations(environment_scope, operation_class, status, updated_at DESC, operation_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_calendar_operations_run ON calendar_operations(environment_scope, run_id, updated_at DESC, operation_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_calendar_operations_workflow ON calendar_operations(environment_scope, workflow_id, updated_at DESC, operation_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_calendar_operations_schedule ON calendar_operations(environment_scope, schedule_id, updated_at DESC, operation_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_calendar_operations_delivery ON calendar_operations(environment_scope, delivery_id, updated_at DESC, operation_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_calendar_operations_event ON calendar_operations(environment_scope, external_event_id, updated_at DESC, operation_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_calendar_artifacts_operation ON calendar_artifacts(environment_scope, operation_id, created_at ASC, artifact_id ASC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_calendar_artifacts_event ON calendar_artifacts(environment_scope, external_event_id, created_at DESC, artifact_id DESC);"#.to_string(),
            ],
        },
        SchemaMigration {
            version: 18,
            name: "mail_domain".to_string(),
            statements: vec![
                r#"CREATE TABLE IF NOT EXISTS mail_accounts (
                    mail_account_id TEXT PRIMARY KEY,
                    integration_id TEXT NOT NULL UNIQUE,
                    environment_scope TEXT NOT NULL,
                    account_key TEXT,
                    readiness_status TEXT NOT NULL,
                    canonical_default INTEGER NOT NULL,
                    updated_at TEXT NOT NULL,
                    document_json TEXT NOT NULL
                );"#.to_string(),
                r#"CREATE TABLE IF NOT EXISTS mail_operations (
                    operation_id TEXT PRIMARY KEY,
                    integration_id TEXT NOT NULL,
                    mail_account_id TEXT NOT NULL,
                    environment_scope TEXT NOT NULL,
                    operation_class TEXT NOT NULL,
                    status TEXT NOT NULL,
                    result_mode TEXT NOT NULL,
                    thread_id TEXT,
                    message_id TEXT,
                    draft_id TEXT,
                    run_id TEXT,
                    workflow_id TEXT,
                    schedule_id TEXT,
                    delivery_id TEXT,
                    updated_at TEXT NOT NULL,
                    document_json TEXT NOT NULL
                );"#.to_string(),
                r#"CREATE TABLE IF NOT EXISTS mail_artifacts (
                    artifact_id TEXT PRIMARY KEY,
                    operation_id TEXT NOT NULL,
                    integration_id TEXT NOT NULL,
                    environment_scope TEXT NOT NULL,
                    kind TEXT NOT NULL,
                    thread_id TEXT,
                    message_id TEXT,
                    draft_id TEXT,
                    attachment_ref_id TEXT,
                    created_at TEXT NOT NULL,
                    document_json TEXT NOT NULL
                );"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_mail_accounts_env_readiness ON mail_accounts(environment_scope, readiness_status, updated_at DESC, integration_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_mail_accounts_env_default ON mail_accounts(environment_scope, account_key, canonical_default, updated_at DESC, integration_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_mail_operations_env_class_status ON mail_operations(environment_scope, operation_class, status, updated_at DESC, operation_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_mail_operations_env_result ON mail_operations(environment_scope, result_mode, updated_at DESC, operation_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_mail_operations_run ON mail_operations(environment_scope, run_id, updated_at DESC, operation_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_mail_operations_workflow ON mail_operations(environment_scope, workflow_id, updated_at DESC, operation_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_mail_operations_schedule ON mail_operations(environment_scope, schedule_id, updated_at DESC, operation_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_mail_operations_delivery ON mail_operations(environment_scope, delivery_id, updated_at DESC, operation_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_mail_operations_thread ON mail_operations(environment_scope, thread_id, updated_at DESC, operation_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_mail_operations_message ON mail_operations(environment_scope, message_id, updated_at DESC, operation_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_mail_operations_draft ON mail_operations(environment_scope, draft_id, updated_at DESC, operation_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_mail_artifacts_operation ON mail_artifacts(environment_scope, operation_id, created_at ASC, artifact_id ASC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_mail_artifacts_thread ON mail_artifacts(environment_scope, thread_id, created_at DESC, artifact_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_mail_artifacts_message ON mail_artifacts(environment_scope, message_id, created_at DESC, artifact_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_mail_artifacts_draft ON mail_artifacts(environment_scope, draft_id, created_at DESC, artifact_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_mail_artifacts_attachment ON mail_artifacts(environment_scope, attachment_ref_id, created_at DESC, artifact_id DESC);"#.to_string(),
            ],
        },
        SchemaMigration {
            version: 19,
            name: "reminder_domain".to_string(),
            statements: vec![
                r#"ALTER TABLE runs ADD COLUMN reminder_id TEXT;"#.to_string(),
                r#"ALTER TABLE runs ADD COLUMN reminder_occurrence_id TEXT;"#.to_string(),
                r#"CREATE TABLE IF NOT EXISTS reminders (
                    reminder_id TEXT PRIMARY KEY,
                    environment_scope TEXT NOT NULL,
                    behavior_mode TEXT NOT NULL,
                    current_state TEXT NOT NULL,
                    next_due_at TEXT,
                    active_occurrence_id TEXT,
                    updated_at TEXT NOT NULL,
                    document_json TEXT NOT NULL
                );"#.to_string(),
                r#"CREATE TABLE IF NOT EXISTS reminder_occurrences (
                    occurrence_id TEXT PRIMARY KEY,
                    reminder_id TEXT NOT NULL,
                    environment_scope TEXT NOT NULL,
                    state TEXT NOT NULL,
                    scheduled_for TEXT NOT NULL,
                    run_id TEXT,
                    workflow_id TEXT,
                    latest_delivery_id TEXT,
                    latest_delivery_status TEXT,
                    updated_at TEXT NOT NULL,
                    document_json TEXT NOT NULL
                );"#.to_string(),
                r#"CREATE TABLE IF NOT EXISTS reminder_actions (
                    action_id TEXT PRIMARY KEY,
                    reminder_id TEXT NOT NULL,
                    occurrence_id TEXT,
                    action_kind TEXT NOT NULL,
                    new_state TEXT,
                    run_id TEXT,
                    workflow_id TEXT,
                    delivery_id TEXT,
                    created_at TEXT NOT NULL,
                    document_json TEXT NOT NULL
                );"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_runs_reminder ON runs(reminder_id, reminder_occurrence_id, created_at DESC, run_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_reminders_env_state ON reminders(environment_scope, current_state, updated_at DESC, reminder_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_reminders_env_due ON reminders(environment_scope, next_due_at, updated_at DESC, reminder_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_rem_occurrences_reminder ON reminder_occurrences(environment_scope, reminder_id, scheduled_for DESC, occurrence_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_rem_occurrences_state ON reminder_occurrences(environment_scope, state, scheduled_for DESC, occurrence_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_rem_occurrences_run ON reminder_occurrences(environment_scope, run_id, updated_at DESC, occurrence_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_rem_occurrences_workflow ON reminder_occurrences(environment_scope, workflow_id, updated_at DESC, occurrence_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_rem_occurrences_delivery ON reminder_occurrences(environment_scope, latest_delivery_id, updated_at DESC, occurrence_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_rem_actions_reminder ON reminder_actions(reminder_id, created_at DESC, action_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_rem_actions_occurrence ON reminder_actions(occurrence_id, created_at DESC, action_id DESC);"#.to_string(),
            ],
        },
        SchemaMigration {
            version: 20,
            name: "evaluation_replay_harness".to_string(),
            statements: vec![
                r#"CREATE TABLE IF NOT EXISTS evaluation_replay_candidates (
                    candidate_id TEXT PRIMARY KEY,
                    environment_scope TEXT NOT NULL,
                    candidate_kind TEXT NOT NULL,
                    source_kind TEXT NOT NULL,
                    source_id TEXT NOT NULL,
                    readiness_status TEXT NOT NULL,
                    latest_attempt_id TEXT,
                    latest_comparison_id TEXT,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL,
                    document_json TEXT NOT NULL
                );"#.to_string(),
                r#"CREATE TABLE IF NOT EXISTS evaluation_replay_attempts (
                    attempt_id TEXT PRIMARY KEY,
                    candidate_id TEXT NOT NULL,
                    environment_scope TEXT NOT NULL,
                    mode TEXT NOT NULL,
                    status TEXT NOT NULL,
                    change_window_label TEXT,
                    baseline_attempt_id TEXT,
                    started_at TEXT,
                    completed_at TEXT,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL,
                    document_json TEXT NOT NULL,
                    FOREIGN KEY(candidate_id) REFERENCES evaluation_replay_candidates(candidate_id) ON DELETE CASCADE
                );"#.to_string(),
                r#"CREATE TABLE IF NOT EXISTS evaluation_comparisons (
                    comparison_id TEXT PRIMARY KEY,
                    candidate_id TEXT NOT NULL,
                    attempt_id TEXT NOT NULL,
                    environment_scope TEXT NOT NULL,
                    terminal_status TEXT NOT NULL,
                    change_window_label TEXT,
                    generated_at TEXT NOT NULL,
                    document_json TEXT NOT NULL,
                    FOREIGN KEY(candidate_id) REFERENCES evaluation_replay_candidates(candidate_id) ON DELETE CASCADE,
                    FOREIGN KEY(attempt_id) REFERENCES evaluation_replay_attempts(attempt_id) ON DELETE CASCADE
                );"#.to_string(),
                r#"CREATE TABLE IF NOT EXISTS evaluation_regression_fixtures (
                    fixture_id TEXT PRIMARY KEY,
                    environment_scope TEXT NOT NULL,
                    domain_class TEXT NOT NULL,
                    candidate_id TEXT,
                    manifest_path TEXT NOT NULL,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL,
                    document_json TEXT NOT NULL
                );"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_eval_candidates_env_ready ON evaluation_replay_candidates(environment_scope, readiness_status, updated_at DESC, candidate_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_eval_candidates_env_kind ON evaluation_replay_candidates(environment_scope, candidate_kind, source_kind, updated_at DESC, candidate_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_eval_attempts_env_candidate ON evaluation_replay_attempts(environment_scope, candidate_id, created_at DESC, attempt_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_eval_attempts_env_status ON evaluation_replay_attempts(environment_scope, status, created_at DESC, attempt_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_eval_comparisons_env_candidate ON evaluation_comparisons(environment_scope, candidate_id, generated_at DESC, comparison_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_eval_comparisons_env_attempt ON evaluation_comparisons(environment_scope, attempt_id, generated_at DESC, comparison_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_eval_fixtures_env_domain ON evaluation_regression_fixtures(environment_scope, domain_class, updated_at DESC, fixture_id DESC);"#.to_string(),
            ],
        },
        SchemaMigration {
            version: 21,
            name: "tenant_identity_access_foundation".to_string(),
            statements: vec![
                r#"ALTER TABLE auth_tokens ADD COLUMN principal_id TEXT;"#.to_string(),
                r#"ALTER TABLE auth_tokens ADD COLUMN status TEXT NOT NULL DEFAULT 'active';"#.to_string(),
                r#"ALTER TABLE auth_tokens ADD COLUMN default_tenant_id TEXT;"#.to_string(),
                r#"ALTER TABLE auth_tokens ADD COLUMN expires_at TEXT;"#.to_string(),
                r#"ALTER TABLE auth_tokens ADD COLUMN revoked_at TEXT;"#.to_string(),
                r#"ALTER TABLE auth_tokens ADD COLUMN rotated_from_token_id TEXT;"#.to_string(),
                r#"ALTER TABLE auth_tokens ADD COLUMN rotated_to_token_id TEXT;"#.to_string(),
                r#"CREATE TABLE IF NOT EXISTS tenants (
                    tenant_id TEXT PRIMARY KEY,
                    tenant_kind TEXT NOT NULL,
                    display_name TEXT NOT NULL,
                    status TEXT NOT NULL,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL,
                    created_by_principal_id TEXT,
                    default_owner_principal_id TEXT
                );"#.to_string(),
                r#"CREATE TABLE IF NOT EXISTS principals (
                    principal_id TEXT PRIMARY KEY,
                    principal_kind TEXT NOT NULL,
                    display_name TEXT NOT NULL,
                    status TEXT NOT NULL,
                    default_tenant_id TEXT NOT NULL,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL,
                    disabled_at TEXT,
                    removed_at TEXT
                );"#.to_string(),
                r#"CREATE TABLE IF NOT EXISTS memberships (
                    membership_id TEXT PRIMARY KEY,
                    tenant_id TEXT NOT NULL,
                    principal_id TEXT NOT NULL,
                    role TEXT NOT NULL,
                    status TEXT NOT NULL,
                    invitation_id TEXT,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL,
                    accepted_at TEXT,
                    removed_at TEXT
                );"#.to_string(),
                r#"CREATE TABLE IF NOT EXISTS tenant_invitations (
                    invitation_id TEXT PRIMARY KEY,
                    tenant_id TEXT NOT NULL,
                    invited_principal_id TEXT NOT NULL,
                    invited_by_principal_id TEXT NOT NULL,
                    role TEXT NOT NULL,
                    status TEXT NOT NULL,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL,
                    expires_at TEXT,
                    decided_at TEXT
                );"#.to_string(),
                r#"CREATE TABLE IF NOT EXISTS token_tenant_grants (
                    grant_id TEXT PRIMARY KEY,
                    token_id TEXT NOT NULL,
                    tenant_id TEXT NOT NULL,
                    is_default INTEGER NOT NULL,
                    status TEXT NOT NULL,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL,
                    revoked_at TEXT,
                    granted_by_principal_id TEXT
                );"#.to_string(),
                r#"CREATE TABLE IF NOT EXISTS tenant_audit_events (
                    audit_event_id TEXT PRIMARY KEY,
                    event_kind TEXT NOT NULL,
                    tenant_id TEXT,
                    principal_id TEXT,
                    target_principal_id TEXT,
                    token_id TEXT,
                    outcome TEXT NOT NULL,
                    reason_code TEXT NOT NULL,
                    created_at TEXT NOT NULL,
                    document_json TEXT
                );"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_tenants_kind_status ON tenants(tenant_kind, status, created_at DESC, tenant_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_principals_status ON principals(status, created_at DESC, principal_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_memberships_tenant_status ON memberships(tenant_id, status, role, principal_id);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_memberships_principal_status ON memberships(principal_id, status, tenant_id);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_invitations_tenant_status ON tenant_invitations(tenant_id, status, created_at DESC, invitation_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_invitations_principal_status ON tenant_invitations(invited_principal_id, status, created_at DESC, invitation_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_token_grants_token_status ON token_tenant_grants(token_id, status, tenant_id);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_token_grants_tenant_status ON token_tenant_grants(tenant_id, status, token_id);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_tenant_audit_events_tenant_created ON tenant_audit_events(tenant_id, created_at DESC, audit_event_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_tenant_audit_events_principal_created ON tenant_audit_events(principal_id, created_at DESC, audit_event_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_tenant_audit_events_token_created ON tenant_audit_events(token_id, created_at DESC, audit_event_id DESC);"#.to_string(),
            ],
        },
        SchemaMigration {
            version: 22,
            name: "tenant_migration_progress".to_string(),
            statements: vec![
                r#"CREATE TABLE IF NOT EXISTS tenant_migration_progress (
                    step_name           TEXT PRIMARY KEY,
                    status              TEXT NOT NULL,
                    started_at          INTEGER,
                    completed_at        INTEGER,
                    last_processed_key  TEXT,
                    error               TEXT
                );"#.to_string(),
            ],
        },
        SchemaMigration {
            version: 23,
            name: "tenant_scope_events_column".to_string(),
            statements: vec![
                r#"ALTER TABLE events ADD COLUMN tenant_id TEXT;"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_events_tenant_time ON events(tenant_id, occurred_at DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_events_tenant_category_time ON events(tenant_id, category, name, occurred_at DESC);"#.to_string(),
            ],
        },
        SchemaMigration {
            version: 24,
            name: "tenant_scope_runtime_columns".to_string(),
            statements: vec![
                r#"ALTER TABLE sessions ADD COLUMN tenant_id TEXT;"#.to_string(),
                r#"ALTER TABLE runs ADD COLUMN tenant_id TEXT;"#.to_string(),
                r#"ALTER TABLE steps ADD COLUMN tenant_id TEXT;"#.to_string(),
                r#"ALTER TABLE tool_calls ADD COLUMN tenant_id TEXT;"#.to_string(),
                r#"ALTER TABLE llm_dispatches ADD COLUMN tenant_id TEXT;"#.to_string(),
                r#"ALTER TABLE checkpoints ADD COLUMN tenant_id TEXT;"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_sessions_tenant_created ON sessions(tenant_id, created_at DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_runs_tenant_created ON runs(tenant_id, created_at DESC, run_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_steps_tenant_run_created ON steps(tenant_id, run_id, created_at DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_tool_calls_tenant_step ON tool_calls(tenant_id, step_id);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_tool_calls_tenant_status_created ON tool_calls(tenant_id, status, created_at DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_llm_dispatches_tenant_created ON llm_dispatches(tenant_id, created_at DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_llm_dispatches_tenant_provider_status ON llm_dispatches(tenant_id, provider, status, created_at DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_checkpoints_tenant_run_captured ON checkpoints(tenant_id, run_id, captured_at DESC);"#.to_string(),
            ],
        },
        SchemaMigration {
            version: 25,
            name: "tenant_scope_schedules_columns".to_string(),
            statements: vec![
                r#"ALTER TABLE schedules ADD COLUMN tenant_id TEXT;"#.to_string(),
                r#"ALTER TABLE schedule_targets ADD COLUMN tenant_id TEXT;"#.to_string(),
                r#"ALTER TABLE schedule_dispatch_attempts ADD COLUMN tenant_id TEXT;"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_schedules_tenant_status_due ON schedules(tenant_id, status, next_due_at, schedule_id);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_schedule_targets_tenant_schedule ON schedule_targets(tenant_id, schedule_id, target_ref_id);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_schedule_attempts_tenant_schedule_due ON schedule_dispatch_attempts(tenant_id, schedule_id, due_at DESC, attempt_id DESC);"#.to_string(),
            ],
        },
        SchemaMigration {
            version: 26,
            name: "tenant_scope_workflows_columns".to_string(),
            statements: vec![
                r#"ALTER TABLE workflows ADD COLUMN tenant_id TEXT;"#.to_string(),
                r#"ALTER TABLE workflow_steps ADD COLUMN tenant_id TEXT;"#.to_string(),
                r#"ALTER TABLE workflow_dependencies ADD COLUMN tenant_id TEXT;"#.to_string(),
                r#"ALTER TABLE workflow_handoffs ADD COLUMN tenant_id TEXT;"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_workflows_tenant_updated ON workflows(tenant_id, updated_at DESC, workflow_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_workflow_steps_tenant_workflow_position ON workflow_steps(tenant_id, workflow_id, position);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_workflow_dependencies_tenant_workflow ON workflow_dependencies(tenant_id, workflow_id);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_workflow_handoffs_tenant_workflow ON workflow_handoffs(tenant_id, workflow_id);"#.to_string(),
            ],
        },
        SchemaMigration {
            version: 27,
            name: "tenant_scope_integrations_delivery_columns".to_string(),
            statements: vec![
                r#"ALTER TABLE integrations ADD COLUMN tenant_id TEXT;"#.to_string(),
                r#"ALTER TABLE delivery_targets ADD COLUMN tenant_id TEXT;"#.to_string(),
                r#"ALTER TABLE delivery_preferences ADD COLUMN tenant_id TEXT;"#.to_string(),
                r#"ALTER TABLE delivery_outcomes ADD COLUMN tenant_id TEXT;"#.to_string(),
                r#"ALTER TABLE delivery_attempts ADD COLUMN tenant_id TEXT;"#.to_string(),
                r#"ALTER TABLE delivery_summary_windows ADD COLUMN tenant_id TEXT;"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_integrations_tenant_domain_account ON integrations(tenant_id, domain_kind, account_key, canonical_default);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_integrations_tenant_readiness ON integrations(tenant_id, readiness_status, updated_at DESC, integration_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_delivery_targets_tenant_status ON delivery_targets(tenant_id, status, updated_at DESC, target_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_delivery_preferences_tenant_scope ON delivery_preferences(tenant_id, scope_kind, integration_id, active, updated_at DESC, preference_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_delivery_outcomes_tenant_updated ON delivery_outcomes(tenant_id, updated_at DESC, delivery_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_delivery_attempts_tenant_delivery ON delivery_attempts(tenant_id, delivery_id, attempt_number ASC, attempt_id ASC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_delivery_summary_windows_tenant_status ON delivery_summary_windows(tenant_id, status, window_ends_at ASC, summary_window_id ASC);"#.to_string(),
            ],
        },
        SchemaMigration {
            version: 28,
            name: "tenant_scope_calendar_columns".to_string(),
            statements: vec![
                r#"ALTER TABLE calendar_accounts ADD COLUMN tenant_id TEXT;"#.to_string(),
                r#"ALTER TABLE calendar_operations ADD COLUMN tenant_id TEXT;"#.to_string(),
                r#"ALTER TABLE calendar_artifacts ADD COLUMN tenant_id TEXT;"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_calendar_accounts_tenant_readiness ON calendar_accounts(tenant_id, readiness_status, updated_at DESC, calendar_account_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_calendar_operations_tenant_account ON calendar_operations(tenant_id, calendar_account_id, updated_at DESC, operation_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_calendar_artifacts_tenant_operation ON calendar_artifacts(tenant_id, operation_id, created_at ASC, artifact_id ASC);"#.to_string(),
            ],
        },
        SchemaMigration {
            version: 29,
            name: "tenant_scope_mail_columns".to_string(),
            statements: vec![
                r#"ALTER TABLE mail_accounts ADD COLUMN tenant_id TEXT;"#.to_string(),
                r#"ALTER TABLE mail_operations ADD COLUMN tenant_id TEXT;"#.to_string(),
                r#"ALTER TABLE mail_artifacts ADD COLUMN tenant_id TEXT;"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_mail_accounts_tenant_readiness ON mail_accounts(tenant_id, readiness_status, updated_at DESC, mail_account_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_mail_operations_tenant_account ON mail_operations(tenant_id, mail_account_id, updated_at DESC, operation_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_mail_artifacts_tenant_operation ON mail_artifacts(tenant_id, operation_id, created_at ASC, artifact_id ASC);"#.to_string(),
            ],
        },
        SchemaMigration {
            version: 30,
            name: "tenant_scope_reminders_columns".to_string(),
            statements: vec![
                r#"ALTER TABLE reminders ADD COLUMN tenant_id TEXT;"#.to_string(),
                r#"ALTER TABLE reminder_occurrences ADD COLUMN tenant_id TEXT;"#.to_string(),
                r#"ALTER TABLE reminder_actions ADD COLUMN tenant_id TEXT;"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_reminders_tenant_state ON reminders(tenant_id, current_state, updated_at DESC, reminder_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_reminders_tenant_due ON reminders(tenant_id, next_due_at, updated_at DESC, reminder_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_reminder_occurrences_tenant_reminder ON reminder_occurrences(tenant_id, reminder_id, scheduled_for DESC, occurrence_id DESC);"#.to_string(),
                r#"CREATE INDEX IF NOT EXISTS idx_reminder_actions_tenant_reminder ON reminder_actions(tenant_id, reminder_id, created_at DESC, action_id DESC);"#.to_string(),
            ],
        },
    ]
}
