[package]
name = "kura-capabilities"
edition.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
kura-adapterrpc.workspace = true
serde.workspace = true
chrono.workspace = true
parking_lot.workspace = true
thiserror.workspace = true

[dev-dependencies]
kura-adapterref.workspace = true
