[package]
license.workspace = true
name = "kura-core"
edition.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
kura-protocol.workspace = true
kura-model-provider.workspace = true
serde_json.workspace = true
thiserror.workspace = true
futures.workspace = true

[dev-dependencies]
tokio.workspace = true
parking_lot.workspace = true
