[package]
license.workspace = true
name = "kura-billing"
edition.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
chrono.workspace = true
tokio = { workspace = true, features = ["sync"] }

[dev-dependencies]
parking_lot.workspace = true
